### ISSUE TITLE
Asp.NetCore Razor Pages- Validator won't be executed when using the BindProperty Attribute

### ISSUE THREAD

**Issue by Metetron** [JeremySkinner/FluentValidation#786] opened 2018-06-15 12:46 UTC
```
    public class BindPropertyCreateModel : PageModel
    {
        [BindProperty]
        public TestModel TestModel { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("../Index");
        }
    }
```

When using the BindProperty- Attribute in a Razor Page, the validator will not be executed.

Writing the PageModel like this works fine:
```
public class CreateModel : PageModel
    {
        public TestModel TestModel { get; set; }

        public IActionResult OnPost(TestModel model)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("../Index");
        }
    }
```

I am using aspnetcore 2.1 and FluentValidation 7.6.102.
I have created a small example to show the behaviour:
[FV_BindProperty_Test.zip](https://github.com/JeremySkinner/FluentValidation/files/2106044/FV_BindProperty_Test.zip)

**Comment by JeremySkinner** [comment] 2018-06-15 17:06
I started having a look at this. It turns out FluentValidation does already support property binding just fine as it uses the same underlying api. 

What's odd is that if I remove the `[BindProperty]` attribute form the `BindPropertyCreateModel`, it still doesn't work. Also, if I add the `[BindProperty]` attribute to the `CreateModel` that *still works*, so the issue isn't related to the attribute.

**Comment by JeremySkinner** [comment] 2018-06-15 17:21
A further update:

It's to do with the model naming. When you use `[BindProperty]` it assumes that the fields have no prefix or binding doesn't occur (ie your elements would have to be called `Name` instead of `TestModel.Name`.) Because your fields have a prefix, you'll need to specify that in the attribute, ie:

```
[BindProperty(Name="TestModel")]
```

Now binding takes place, but validation still isn't running. I'll look at that now....

**Comment by JeremySkinner** [comment] 2018-06-15 19:51
I found the issue; FluentValidation's default behaviour is not to perform implicit validation of child properties, but this is not compatible with `BindProperty` as the MVC metadata api essentially treats a top-level property on the PageModel and a property on the bound model as the same.

You can work around it for now by enabling implicit validation in FluentValidation's startup routine:

```
services.AddMvc().AddFluentValidation(fv => {
  fv.ImplicitlyValidateChildProperties = true;
});

```

I'll work on getting a fix out so this isn't necessary, but hopefully this should be enough to work around the issue for now. 

Thanks again for reporting this.

**Comment by Metetron** [comment] 2018-06-15 20:08
Thanks for your help. I applied your solution to my application and it works fine now.

**Comment by JeremySkinner** [comment] 2018-06-16 16:33
I've pushed out 7.6.103 to nuget with a fix for this, so you shouldn't need to enable implicit validation anymore (unless you need it). Please give it a try and let me know if you run into any issues.

**Closed by JeremySkinner** 2018-06-16 16:33 UTC
