### ISSUE TITLE
The ShouldHaveValidationErrorFor method fails in a unit test for a validator that calls the .When( .. ) method

### ISSUE THREAD

**Issue by PureKrome** [JeremySkinner/FluentValidation#186] opened 2016-01-05 12:40 UTC
G'Day :wave: I've just upgraded my repo from v5.6.2.0 to v6.0.0.0.

Previously, my validators all worked fine but now my `.When(...)` is failing to chain/work properly. 

[This is the validator](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/Code/OpenRealEstate.Validation/AddressValidator.cs#L13-L15) that now errors:

```
public class AddressValidator : AbstractValidator<Address>
{
    public static string RuleLocationNames = "LocationNames";

    public AddressValidator()
    {
        // Cannot have a street number/lot and no street name.
        RuleFor(address => address.Street)
            .NotNull()
            .When(address => !string.IsNullOrWhiteSpace(address.StreetNumber))
            .WithMessage("A street name is required when a street number has been provided. Eg. Smith Street.");

        // <the other rules are snipped out for brevity>
    }
}
```

And [this is the unit test](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/Code/OpenRealEstate.Tests/Validators/AddressValidatorFacts.cs#L38) which now fails ...

```
[Fact]
public void GivenAStreetNumberAndNoStreetName_Validate_ShouldHaveAValidationError()
{
    // Arrange.
    var address = new Address{ StreetNumber = "a" };

    // Act & Assert.
    var result = _addressValidator.ShouldHaveValidationErrorFor(a => a.Street, address);
}
```

The error is that *no validation error was thrown* when in this scenario, it should have. In this unit test, I'm providing an instance of an address, where the `Street` property is `null`.

![image](https://cloud.githubusercontent.com/assets/899878/12115230/772e9534-b404-11e5-8d94-a5d5257529d2.png)

Now, if i _manually_ call the `Validation` method by adding in a new line of code to test this ...  it works (yay!) ...
eg: `var blahBlah = _addressValidator.Validate(address);`

![image](https://cloud.githubusercontent.com/assets/899878/12115265/cf84a372-b404-11e5-9c51-464fb5812817.png)

Ok - so THAT'S good... but why does the next line of code, fail ?

eg: `var result = _addressValidator.ShouldHaveValidationErrorFor(a => a.Street, address);`

![image](https://cloud.githubusercontent.com/assets/899878/12115277/f5093dba-b404-11e5-980e-ee339df24383.png)

When I commented out the `.When(...)` line in my the validator's `RuleFor` line/setup, then `.ShouldHaveValidationErrorFor` correctly works. But that's not good enough because my logic requires the `.When(..)` chained method :cry: 

Can you help, @JeremySkinner ?

Before I posted this, I tried to download the latest code from this repo and build the main project so I could then hopefully, locally, debug-and-step-through this method against my code .. but alas it didn't compile with all these weird vnext errors (yes, i'm in VS2015 and i tried both the 2015 solution and the !2015 solution).

You can repo this error by downloading the latest commit for the `dev` branch from [my OSS repo](https://github.com/OpenRealEstate/OpenRealEstate.NET) where this is erroring in.

![](http://www.yentelman.com/wp-content/uploads/2014/12/help-me-obi-wan.gif)

**Comment by PureKrome** [comment] 2016-01-05 12:46
Oh - [this other unit test](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/Code/OpenRealEstate.Tests/Validators/UnitOfMeasureValidatorFacts.cs#L53) also fails. 

```
[Fact]
public void GivenAValueButNoType_Validate_ShouldHaveValidationErrors()
{
    // Arrange.
    var unitOfMeasure = new UnitOfMeasure
    {
        Value = 1
    };

    // Act & Assert.
    _unitOfMeasureValidator.ShouldHaveValidationErrorFor(unit => unit.Type, unitOfMeasure);
}
```
[That corresponding validator](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/Code/OpenRealEstate.Validation/UnitOfMeasureValidator.cs#L12-L14) has the same `When( .. )` method chained in there. Which is why I think this is the cause:

```
public class UnitOfMeasureValidator : AbstractValidator<UnitOfMeasure>
    {
        public UnitOfMeasureValidator()
        {
            RuleFor(unit => unit.Value).GreaterThanOrEqualTo(0);

            RuleFor(unit => unit.Type).NotNull()
                .When(unit => unit.Value > 0)
                .WithMessage("If a unit of measure's 'Value' is provided, then a 'Type' also needs to be provided.");
        }
    }
```

**Comment by Ciget** [comment] 2016-01-05 12:57
Yep, i have the same stuff(

**Comment by JeremySkinner** [comment] 2016-01-05 13:04
The behaviour of When hasn't changed; I think the problem is in the TestHelper giving an incorrect message. There was a contribution that added a lot of new functionality to the TestHelper, so I expect the testing is broken, but the actual code is correct. I'll confirm this and post an update.

**Comment by PureKrome** [comment] 2016-01-05 13:15
Thanks @JeremySkinner for the prompt reply. Also, thanks @Ciget for jumping in, giving weight to this issue.

I agree that i think `.When(..)` is working ok - when I call the `.Validate(..)` method directly, it works. 

I'll update the title, to reflect this point.

**Comment by JeremySkinner** [comment] 2016-01-05 13:26
Yes the testhelper was broken - the overload for taking an explicit object to validate (rather than a property value) was internally using the wrong overload. I've jsut checked in a fix and pushed to nuget. Please update and let me know if this is working for you.

**Comment by PureKrome** [comment] 2016-01-05 13:43
Those both pass now :)

but this fails: `ShouldNotHaveValidationErrorFor` ... can u check the opposite logic, in there plz?

**Comment by JeremySkinner** [comment] 2016-01-05 13:46
ShouldNotHaveValidationErrorFor had the same problem but I fixed it in the same update. Could you post a test if you're not seeing this working as expected?

**Comment by PureKrome** [comment] 2016-01-05 13:47
posted above.

**Comment by JeremySkinner** [comment] 2016-01-05 13:50
That passed for me

**Comment by PureKrome** [comment] 2016-01-05 13:51
![image](https://cloud.githubusercontent.com/assets/899878/12116663/9ae18b52-b40f-11e5-8f85-88d4d77b523f.png)

**Comment by JeremySkinner** [comment] 2016-01-05 13:52
You're definitely on 6.0.1?

This is the code I used (same as yours, just renamed the classes):

```

public class Address2 {
	public string StreetNumber { get; set; }
	public string Street { get; set; }
}

public class Address2Validator : AbstractValidator<Address2>
{
	public static string RuleLocationNames = "LocationNames";

	public Address2Validator()
	{
		// Cannot have a street number/lot and no street name.
		RuleFor(address => address.Street)
			.NotNull()
			.When(address => !string.IsNullOrWhiteSpace(address.StreetNumber))
			.WithMessage("A street name is required when a street number has been provided. Eg. Smith Street.");
	}
}
```

```
[Fact]
public void ShouldNotHaveValidationError_should_correctly_handle_explicitly_providing_object_to_validate()
{
	var validator = new Address2Validator();
	var address = new Address2
	{
		StreetNumber = "a",
		Street = "b"
	};

	validator.ShouldNotHaveValidationErrorFor(a => a.Street, address);
}
```

**Comment by PureKrome** [comment] 2016-01-05 13:57
yep - sure am.

![image](https://cloud.githubusercontent.com/assets/899878/12116788/6912a844-b410-11e5-81c6-dd4cd4179e80.png)


le sniffles...

**Comment by JeremySkinner** [comment] 2016-01-05 13:58
Very odd. If you copy and paste my test code does it still fail for you?

**Comment by PureKrome** [comment] 2016-01-05 14:02
Copy/pasted your test code - :white_check_mark: 
My unit test: :x: 

The difference (possibly) is that mine ([Address.cs](https://github.com/OpenRealEstate/OpenRealEstate.NET/blob/dev/Code/OpenRealEstate.Core/Models/Address.cs) has a bunch of OTHER properties and my validator also find 3 errors with them.

**Comment by JeremySkinner** [comment] 2016-01-05 14:11
Yep, that's why. Let me get that fixed

**Comment by JeremySkinner** [comment] 2016-01-05 14:19
OK I've done another build...try now?

**Comment by PureKrome** [comment] 2016-01-05 14:23
![](https://31.media.tumblr.com/83d94bc644289d810ea45d31c3e0eb50/tumblr_inline_n5a8nwNd161solpjm.gif)

we're good again!

thank you sir!

**Comment by JeremySkinner** [comment] 2016-01-05 14:24
Great! Sorry about that. Clearly my test coverage of the test helper wasn't very good! Anyway got some better tests in there now and hopefully shouldn't happen again.

**Closed by JeremySkinner** 2016-01-05 14:24 UTC
