### ISSUE TITLE
Chaining conditional validations does not work

### ISSUE THREAD

**Issue by christopheblin** [JeremySkinner/FluentValidation#1291] opened 2019-12-30 13:00 UTC
### System Details

- FluentValidation version: 8.6.0

### Issue Description

Here is a test case that fails (whereas I think it should pass)

```
using FluentAssertions;
using FluentValidation;
using Xunit;

namespace DiagnosticProcedures.Tests
{
    public class Tmp
    {
        [Fact]
        public void Test()
        {
            //the following 3 assertions work as expected
            //new MyFormValidator().Validate(new MyForm() { A = "notempty", B = "" }).IsValid.Should().Be(true);
            //new MyFormValidator().Validate(new MyForm() { A = "", B = "notempty" }).IsValid.Should().Be(true);
            //new MyFormValidator().Validate(new MyForm() { A = "notempty", B = "notempty" }).IsValid.Should().Be(false);

            new MyFormValidator().Validate(new MyForm() { A = "", B = "" }).IsValid.Should().Be(false);
        }
    }

    public class MyForm
    {
        public string A { get; set; }
        public string B { get; set; }
    }

    public class MyFormValidator : AbstractValidator<MyForm>
    {
        public MyFormValidator()
        {
            RuleFor(x => x.B)
                .NotEmpty().When(x => x.A == "")
                .Empty().When(x => x.A != "");
        }
    }
}

```

Note that, as a workaround, using separate rules work:

        public MyFormValidator()
        {
            RuleFor(x => x.B).NotEmpty().When(x => x.A == "");
            RuleFor(x => x.B).Empty().When(x => x.A != "");
        }

**Comment by JeremySkinner** [comment] 2019-12-30 13:10
Conditions apply to *all* previous validators in the same chain. There’s a second parameter to When that allows you to specify that it should only apply to the immediately preceding validator.

**Comment by christopheblin** [comment] 2019-12-30 13:14
Ah thanks for the fast answer !

Maybe could be added in https://fluentvalidation.net/start#conditions ?

How can I do a PR on the doc ?

**Comment by JeremySkinner** [comment] 2019-12-30 13:15
Thanks - a PR would be great. All the documentation is in the docs folder in the repo

**Comment by christopheblin** [comment] 2019-12-30 13:43
Here you are :)

Note that it may be a great addition to have something like `ApplyConditionTo.AllUnconditionedPreviousValidators`

That way, we'll be able to do

```csharp
RuleFor(customer => customer.Photo)
    .NotEmpty().Matches("https://wwww.photos.io/\d+\.png").When(customer => customer.IsPreferredCustomer, ApplyConditionTo.AllUnconditionedPreviousValidators)
    .Empty().When(customer => ! customer.IsPreferredCustomer, ApplyConditionTo.AllUnconditionedPreviousValidators);
```

That way, you can chain rules for a specific condition.

Also note that, the WithMessage has the "opposite problem":

            RuleFor(x => x.Name)
                .NotEmpty().WithMessage(_ => localizer.InvalidName())
                .MaximumLength(150).WithMessage(_ => localizer.InvalidName());

You are required to repeat WithMessage for each rule (like the default is ApplyMessageTo.CurrentValidator).

Great library otherwise, keep up the good work !

**Comment by JeremySkinner** [comment] 2019-12-30 14:30
Thanks, I've merged the PR with a few wording changes. 

> Note that it may be a great addition to have something like ApplyConditionTo.AllUnconditionedPreviousValidators

I'm not really keen on this as I don't think it's particularly clear what's happening. In this situation I'd just break it up into multiple calls to `RuleFor`, all with separate conditions (which can all then be left on the default behaviour). This is much more readable than trying to shoehorn everything into a single chain. 

> Also note that, the WithMessage has the "opposite problem":

I wouldn't consider this a problem - it's by design. Messages and conditions have separate goals, and their usual use cases are different. A message is *generally* different for each validator in the chain. Obviously everyone's applications are different, but most of the time in most projects I've worked with the expectation is generally that you'd want different messages depending on the MaxLength failing vs the NotEmpty failing ("Please enter a name" vs "The name you entered is too long. Please ensure that it's less than 150 characters (you entered 200 characters"). 

A condition however usually applies to multiple validators in a single chain (eg "Check that the username isn't too long, and also check that it's not already in use, but only if it's been specified"). Of course there are exceptions (which is why ApplyConditionTo.CurrentValidator exists), but this is generally unusual, as multiple calls to RuleFor with separate conditions are much more readable.  

FluentValidation's default behaviour has come about over the last 11 years of real world usage, and I'm happy that the defaults for both conditions and messages are sensible. 

Thanks for the feedback though!

**Closed by JeremySkinner** 2019-12-30 14:30 UTC
