### ISSUE TITLE
Problem with overriding default validator for a child property. InterceptorValidator only works on MVC project.

### ISSUE THREAD

**Issue by abhay8** [JeremySkinner/FluentValidation#168] opened 2015-11-20 13:56 UTC
Hi,

I need the parent validator to override rules for a child. I only need interceptor because FluentValidation applies child validation rules automatically. If your parent object doesn't want validation to be applied on the child object (or need a different RuleSet), there is no other way to remove the child validator.
For example, I want to do something like this

```
[Validator(typeof(VehicleValidator)]
public class Vehicle
{
     ...
     Address VehicleAddress {get; set;}

     bool VehicleIsKeptAtHome {get; set;}
}

[Validator(typeof(AddressValidator)]
public class Address : IAddress
{
    //
     String Address_Line_1 {get; set;}
     String Address_Line_2 {get; set;}
     ...

}

public class VehicleValidator : AbstractValidator<Parent>    {
        public VehicleValidator ()
        {
              ....
            RuleFor(x => x.VehicleAddress)
                .SetValidator(new IgnoreAddressValidator())
                .When(r => r.VehicleIsKeptAtHome == true);

            RuleFor(x => x.VehicleAddress)
                .SetValidator(new AddressValidator())
                .When(r => r.VehicleIsKeptAtHome == false);

        }
    }
```

The following InterceptorValidator solves the problem.. But, not suitable for WebApi project.

```
     public class AddressValidationInterceptor<TAddress> : IValidatorInterceptor 
        where TAddress: IAddress
    {
        public ValidationResult AfterMvcValidation(ControllerContext controllerContext, ValidationContext validationContext, ValidationResult result)
        {
            return result;
        }

        public ValidationContext BeforeMvcValidation(ControllerContext controllerContext, ValidationContext validationContext)
        {
            var instance = validationContext.InstanceToValidate;
            if (instance is TAddress)
            {

                //return empty result set
                return validationContext.Clone(selector: new       RulesetValidatorSelector("ApplyParentRules"));
            }

            return validationContext;

        }

    }
```

And.. Then I simply added an empty RuleSet with name "ApplyParentRules" on the AddressValidtor.

```
    public class AddressValidator : AbstractValidator<IAddress>
    {
        public AddressValidator()
        {
            RuleFor(x => x.Address_1)
                .NotEmpty()

....

            RuleFor(x => x.Country)
                .NotEmpty()
                .WithLocalizedMessage(() => ContactResources.Personal_Contact_Country_Error_Empty);

            RuleSet("ApplyParentRules", () => { });
         }
}
```

I want Vehicle Address to be validated only if vehicle is NOT kept at home. Address model is also used in tons of other objects, such as HomeAddress, WorkAddress and in all other cases its absolutely mandatory field. I just needed to create exception just for the Vehicle model. But, FluentValidator always validates Address using AddressValidator and overrides the rules specified in the parent object's validator. This is why I wrote IValidatorInterceptor... But sadly, this only works on MVC project.. But, when the same model is validated on WebApi side, it ignores the interceptor and fails the validation. 

I think there should be an easy way to unset a default validator for child property and replace that with another custom validator... Or may be, when the parent validator sets a validator for its child property, the default validator for that child object shouldn't be invoked..In that case, there won't be any need for IValidatorInterceptor... Not sure about the best approach! 

For time being, I can easily work around this in the controller action code.. Please let me know if there is another way of dealing with this problem.

Regards,
Abhay

**Comment by pavlalexandr** [comment] 2016-08-08 16:21
I faced the same problem. Would really to have a such solution for webApi.

**Comment by neilduncan** [comment] 2017-01-23 10:31
+1

I have an almost identical requirement. I need to validate a delivery address only if they've not checked a "use billing address" flag.

**Comment by JeremySkinner** [comment] 2017-01-23 10:37
@neilduncan FV already supports this...just use a When clause that applies a condition to your SetValidator call.

**Comment by neilduncan** [comment] 2017-01-23 10:43
@JeremySkinner - yeah, I've tried that and not had any luck. 

I'll see if I can get a proper reproduction case for you (or verify that it's a screw-up by me).

**Comment by JeremySkinner** [comment] 2017-01-23 10:45
@neilduncan If you're using MVC, make sure you don't have the child validator annotated with a ValidatorAttribute, that way it'll only be called during a call to SetValidator, and not "transparently" by MVC's pipeline.

**Comment by neilduncan** [comment] 2017-01-23 11:02
Yeah, I can't reproduce it in a vanilla test project without all the MVC auto-wiring. 

In the main project, I'm using an IOC ValidatorFactory, so I guess it's validating both addresses before it gets a chance to evaluate the When clause. 

Either way, I'd like to be able to use my AddressValidator "transparently" most of the time, and **just** turn it off in specific circumstances.

**Comment by JeremySkinner** [comment] 2017-01-23 11:06
I'd really suggest that you have it one way or the other....either register the child validator with your and don't use SetValidator, or use SetValidator and don't register it with the container. 

Trying to do both not only breaks things but is also incredibly confusing....it's really better to standardise on one way or the other. If you need both then use two separate validator classes- that way you're being explicit about your intention.

**Comment by neilduncan** [comment] 2017-01-23 11:20
Ok, removing the AddressValidator registration works, so I'll run with that for now. 

I think my preference would be for the approach suggested by @abhay8 originally. 
>  may be, when the parent validator sets a validator for its child property, the default validator for that child object shouldn't be invoked

At the moment, it seems unclear (to me at least) what happens if you've called SetValidator explicitly. 
Does it use the default Validator for this type, coming from the Factory? The one configured in SetValidator? Both?

**Comment by neilduncan** [comment] 2017-01-23 11:21
@JeremySkinner - thanks for your help, incidentally! I just realised I'd not actually said that at any point :)

**Comment by JeremySkinner** [comment] 2017-01-23 11:27
So SetValidator is completely separate from the transparent validation. If you call SetValidator, then the instance passed to SetValidator will be used.

MVC's validation process will independently examine every type in the request and validate it. So the MVC pipeline works like this:

1) MVC encounters parent model
2) MVC validates each property of parent model (FV not involved)
3) MVC encounters Child Model
4) MVC validates each property of child model
5) MVC sets all properties of child model
6) MVC asks FV for a ChildModelValidator, if one is registered in your container. 
7) FV runs child model rules, if a validator was found in #6. 
8) If #2 has passed, MVC asks FV for a ParentModel validator. 
9) FV runs all rules in the ParentModelValidator
9a) FV encounters a SetValidator call 
9b) FV runs the child validator that was assigned to the SetValidator call

So essentially there are 2 distinct processes running. There's the "FV way" using SetValidator, but independently for this MVC will ask the validator provider for a validator for *every type it encounters during the binding process*, essentially bypassing FV's own way of doing things, and instantiating the child validator directly. 

I would love if I could turn this off and enforce usage of SetValidator, but sadly this isn't possible with regular MVC (the MVC integration for .NET core works this way though).

**Closed** 2018-01-14 11:26 UTC
Labels: Type: Problem
