### ISSUE TITLE
Nuget package without language resources

### ISSUE THREAD

**Issue by nvivo** [JeremySkinner/FluentValidation#386] opened 2017-01-25 15:21 UTC
It would be nice to be able to install the nuget package for fluent validation and have only the core assembly,  and not a dozen folders for resources of languages we won't use. The current files pollute the output folder a lot. 

Since resources are extremely small, it would be even acceptable to embedd all resources in the main library as an alternative.

**Comment by JeremySkinner** [comment] 2017-01-25 15:59
Thanks for the suggestion. I've had a few discussions about this, but in the end decided that it'd stay as-is. If you don't want the resource dlls then I'd suggest adding a post-build step that removes them...there's a sample for how to set this up in this issue: https://github.com/JeremySkinner/FluentValidation/issues/254

**Comment by nvivo** [comment] 2017-01-25 16:27
Ok.  Still think it's a mess this way.  But I'm closing the issue as this has been resolved.

**Comment by waynebrantley** [comment] 2017-03-24 14:06
@JeremySkinner Can we revisit this?
I was using a package with similar issues.  

Basically you would create ''FluentValidation.Core'' and that would contain no language resources.  Just the core code with the default English strings.
You would than take the current ''FluentValidation'' package and remove the fluent code from it replacing that with a reference to the ''FluentValidation.Core' package.

- This is a backward compatible solution.  Everything still works as normal for everyone.
- Those of us not wanting all those resource dlls simply change our dependency from ``FluentValidation`` to 'FluentValiation.core``.

https://github.com/Humanizr/Humanizer#specify-lang

This would end this whole pain in the neck once and for all?

**Comment by JeremySkinner** [comment] 2017-03-24 14:08
To be honest I don't see this as a problem. The localized files have no impact on the application, you can just ignore them. If you really, really don't want them there, they're easy to remove. Not keen on the added workload for something that's really a non-issue.

**Comment by JeremySkinner** [comment] 2017-03-24 14:20
Just to clarify I'm not against doing the work provided that there's a real tangible reason to do so. Are there any real issues caused by having the language files present (other than just 'there are more files')?

**Comment by waynebrantley** [comment] 2017-03-24 14:45
To be honest not really.  It is just more of a reason to reduce what you are dependent on, what is included in the final builds, etc.   

I currently have this pasted 'after build' script in tons of solutions...it is missing in some, in others, missing a language or two in others - and potentially deleting other language folders from other packages in others.

So it is just a real mess to get it cleaned up.
Further when I package up my project for deployment there are warnings about missing files from the package (because I removed them after build!) and I don't like warnings.

It does not seem like a ton of work and you know it has been a popular topic and problem.  I just felt like  this humanizer based solution worked really well for everyone and never have to bring this up again (or update tons of build scripts when you add a language, etc).

So - no 'silver bullet' for must be done....  thoughts?

**Comment by nvivo** [comment] 2017-03-24 14:47
@JeremySkinner  If you're looking for an answer like "this prevents me from using the library", I don't think there is going to be one. It's just odd and unnecessary.

I know I am a little bothered by those language folders I need to see everyday during publish and that I know don't need to be there. It bothers me a little to look at the build logs everyday and half of the lines are these resources. I'm also bothered by the fact that FluentValidation is the only library I see using this anti-pattern. Any library splits i18n resources in a different package, and most libraries today prefer opt-in instead of opt-out.

Not to mention that the opt-out methods requires knowledge of the files I don't want there. Once a new language is added, we need to go there and change the build process. Yes, I could add some coding delete all except the core dll... but see? This little thing is making things more complicated than they should be. I don't to keep adding custom code to every project just to delete files that shouldn't be there in the first place. 

Now, I'm not bothered enough to fight over this, it's such a small thing. I'm just posting because you asked for reasons. I just think it's a very odd choice. But your library, your rules.

**Comment by JeremySkinner** [comment] 2017-03-24 14:56
Thank you both for the feedback, I do appreciate it.

I'm currently in the middle of migrating the project & solution format to netstandard (and as part of that, automatic package creation rather than using my own scripts), but once that's all done I'll take another look at this. 

An FV.Core package wouldn't really work thoughas is it breaks the dependency chain for integration packages. Eg FluentValidation.MVC5, FluentValidation.WebApi FluentValidation.AspNetCore would still depend on the standard FluentValidation, so you'd still get the resources if you depended on any of the integration packages.

I think if we're going to do this, then we do it "properly" and treat it as a breaking change. The main FluentValidation package would have no resources and there would be a separate FV.Languages that contain all the localized dlls. The FV.MVC5/aspnetcore integration packages would depend on FV, thereby allowing the user to opt-in to the languages if they want them by explictly installing FV.Languages. 

Let me know what you think.

**Comment by nvivo** [comment] 2017-03-24 15:09
I think this is a good solution. Worst case scenario someone updates their app without reading the release notes and some strings appear in english. And as you're probably bumping the major version for netstandard, adding this breaking change wouldn't hurt.

**Comment by waynebrantley** [comment] 2017-03-26 19:12
That would work just fine too.  Thanks for reconsidering this.

**Comment by JeremySkinner** [comment] 2017-04-07 13:47
Just a quick update on this. I've now finished the migration to netstandard and the new format project files (see FV 7.0.0-beta1). One thing I noticed as part of this, is creating a nuget package from within VS (or from msbuild using the Pack target) *doesn't* include the satellite assemblies in the package. 

At first I wasn't sure whether or not this is intentional, but it actually appears to be a nuget bug (see https://github.com/NuGet/NuGet.Client/pull/1255) which has been fixed, but isn't yet released. Once nuget has been updated, if we want to go ahead with this then we'll need some way of excluding the satellite assemblies from the package creation process. I don't have the time to research how to do this at the moment, so if either of you are able to find some time that'd be great.

**Comment by JeremySkinner** [comment] 2017-04-13 14:01
Bad news on this I'm afraid.

I did some research (see the separate-languages-package branch). While it's fairly straightforward to create a FluentValidation.Languages package that contains all the localized dlls, they do *not* get copied into consuming project's bin directory. This is a shame - the only way the localized dlls will get pulled in is if they're included in the main package (like now) or by having a separate package per locale (which I greatly dislike). I don't like the approach taken by Humanizr at all - it seems like a mess and still has the disadvantage of having to maintain a huge number of satellite nuget packages. 

If any of you can think of a way to force nuget to copy the satellite assemblies from an all-languages package then I'd love to hear some ideas.

**Comment by waynebrantley** [comment] 2017-04-13 19:30
Hum....I think the separate packages per locale is a bit overkill.
I find it odd the localized are not copied into the project...why would that be?

IStringLocalizer - I took a quick look at this (not dealing with locales myself, was not familiar with it) and I think with your core implementation this is the way to go.   

Would the resource files be available as XML files in the github source so users that were using it could simply download ad add to their project?   They could easily change or add new ones - so that is a bonus.

The more I think about it the more I like it.  Do you think that is a big undertaking to use this in your core versions?

**Comment by JeremySkinner** [comment] 2017-04-13 19:41
> I find it odd the localized are not copied into the project...why would that be?
I think it just seems to be the nuget convention. It'll either pull in the satellite assembly if it's in a single-satellite-per-package package (where the package name follows the format of package.lang.nupkg) or it'll pull in the satellite assemblies if they match the root dll in the package. But if there's no root dll (as in the case of the FluentValidation.Languages package that I tried to create), then they just get ignored when another project references the package! 

> Would the resource files be available as XML files in the github source so users that were using it could simply download ad add to their project?

Yes, so I'd use the exact same resource files that I have now, but I'd have to change the file extension (from foo.lang.resx to something like foo_lang.xml) to stop the satellite assemblies from being generated. Instead of using the standard .net ResourceManager, I'd use some a custom class that can read the embedded xml out of the assembly.

From the point of view of someone using FV, it shouldn't affect anything. You can still use FV as-is, the language will still automatically be switched to reflect the current UI culture, and you can still continue to use your own satellite assemblies if you want to customize the error messages using this approach still. 

The thing that makes me nervous is having to re-implement a lot of what ResourceManager does. We'd be moving from something that's tried-and-tested and stable to something completely new.

**Comment by waynebrantley** [comment] 2017-04-13 19:44
>> The thing that makes me nervous is having to re-implement a lot of what ResourceManager does. We'd be moving from something that's tried-and-tested and stable to something completely new

Yet you moved to .net core  😄 

Seriously, I hear you...However being this is evidently now the way to do it, actually makes sense?

If I have not told you lately...this is one of my favorite libraries and we absolutely love it and use it all over the place.  Thanks for all your work/contributions.

**Comment by JeremySkinner** [comment] 2017-04-13 19:47
> Yet you moved to .net core 😄

Only the AspNetCore integration package targets .net core. The main assembly is produced for standard .net (net45) as well as netstandard1.0 :)

> Seriously, I hear you...However being this is evidently now the way to do it, actually makes sense?

So the default implementation of IStringLocalizer still uses ResourceManager internally, but can be swapped out for other implementations (eg from a database or some other source)

> If I have not told you lately...this is one of my favorite libraries and we absolutely love it and use it all over the place. Thanks for all your work/contributions.

Well thank you for continuing to use it!

**Comment by JeremySkinner** [comment] 2017-04-13 21:03
A very simple solution could actually be to do away with the resx files entirely. The advantage of resx/satellite assemblies is you can deploy them without recompiling the main dll, but in FV's case this really isn't relevant as the only time realistically the translations are going to change is when I do a new release. 

A simple class-per-language might actually work well. This would still be pretty easy for people to contribute translations:

```
public class FrenchLanguage : Language {
	public override string Name => "fr";

	public FrenchLanguage() {
		Translations[nameof(NotNullValidator)] = "'{PropertyName}' ne doit pas avoir la valeur null.";
		Translations[nameof(NotEqualValidator)] = "'{PropertyName}' ne doit pas être égal à '{ComparisonValue}'.";
		// etc
	}

}

public abstract class Language {
		public abstract string Name { get; }
		public Dictionary<string,string> Translations { get; private set; } = new Dictionary<string, string>();

		private static Dictionary<string, Language> _languages = new Dictionary<string, Language>();

		static Language() {
			var languages = new Language[] {
				new EnglishLanguage(),
				new FrenchLanguage(),
				new ItalianLanguage() //etc
			};

			foreach (var language in languages) {
				_languages[language.Name] = language;
			}
		}

		public static string GetString(string key, CultureInfo culture) {
			culture = culture ?? CultureInfo.CurrentUICulture;

			string code = culture.Name;

			if (! culture.IsNeutralCulture) {
				code = culture.Parent.Name;
			}

			if (_languages.ContainsKey(code)) {
				code = "en";
			}

			string value = null;

			if (!_languages.ContainsKey(code) || !_languages[code].Translations.TryGetValue(key, out value)) {
				_languages["en"].Translations.TryGetValue(key, out value);
			}

			return value ?? string.Empty;
		}
	}
```

**Comment by waynebrantley** [comment] 2017-04-14 02:09
Well, it is pretty simple, but non-standard....but easy and simple and like you said zero reason to update languages unless a new release comes out.

Is there a default or does everything go through this language service?  I guess no difference performance than what happens now?

**Comment by JeremySkinner** [comment] 2017-04-14 12:48
All messages and display names would go through an IStringSource as they do now, but the default implementation of this would be one that goes through the language service (default lanagage would be en) instead of the OverridableLocalizableStringSource which is the default at the moment (which uses ResourceManager based on a type/name). That way there's no breaking change to PropertyRule or PropertyValidator. 

The only breaking change would be to ValidatorOptions.ResourceProviderType (which is currently used as a global way of replacing all of FV's default messages). I'm thinking of just removing this entirely (or at least marking it as obsolete), and users could instead replace the default messages by calling into the language service in app startup.

**Comment by JeremySkinner** [comment] 2017-04-14 18:17
I've committed the changes for this: https://github.com/JeremySkinner/FluentValidation/commit/341dac4879634fb3261b7bb559aa09b062681b16

Would appreciate a code review if you have time.

**Comment by JeremySkinner** [comment] 2017-04-17 12:41
(This is also in 7.0-beta2)

**Comment by waynebrantley** [comment] 2017-04-17 19:34
I reviewed the code.  I could not do an actual review (like on a normal pull request), but added a few comments to the code on the commit.

**Comment by JeremySkinner** [comment] 2017-05-19 18:23
7.0 is out with the new localization support, and I've updated the docs so I'm closing this issue. Please open a separate issue if you run into any problems with this.

**Closed by JeremySkinner** 2017-05-19 18:23 UTC
