### ISSUE TITLE
Validation crashes for every rule (RuleFor(…).XXX())

### ISSUE THREAD

**Issue by PaulAchess** [JeremySkinner/FluentValidation#70] opened 2015-05-25 14:17 UTC
Hi, I was trying to use my app after migrating fluentvalidation and I experienced a crash at the very creation of the RuleFor() of my Validator. This crashes for all the Rules and seems to be a bug on CreateDelegate, even though I could not understand why this would crash.

My structure is the following:
* ViewModels (and validation) on a PCL Project, views made with Xamarin.Forms
* Specific project for each platform.

This seems not to crash on Android.

The exception is an `ArgumentException`, with message `"method argument length mismatch"`

Here is the stacktrace for « .Email() »:

    at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed) [0x0011b] in corlib/System/Delegate.cs:293
    at System.Reflection.MethodInfo.CreateDelegate (System.Type delegateType, System.Object target) [0x00000] in src\FluentValidation\Internal\Compatibility.cs:55
    at FluentValidation.Resources.StaticResourceAccessorBuilder.GetResourceAccessor (System.Type resourceType, System.String resourceName) [0x00064] in \src\FluentValidation\Resources\IResourceAccessorBuilder.cs:42 
    at FluentValidation.Resources.LocalizedStringSource..ctor (System.Type resourceType, System.String resourceName, IResourceAccessorBuilder resourceAccessorBuilder) [0x00006] in \src\FluentValidation\Resources\LocalizedStringSource.cs:40
    at FluentValidation.Resources.LocalizedStringSource.CreateFromExpression (System.Linq.Expressions.Expression1 expression, IResourceAccessorBuilder resourceProviderSelectionStrategy) [0x00043] in \src\FluentValidation\Resources\LocalizedStringSource.cs:68
    at FluentValidation.Validators.PropertyValidator..ctor (System.Linq.Expressions.Expression1 errorMessageResourceSelector) [0x00011] in \src\FluentValidation\Validators\PropertyValidator.cs:54
    at FluentValidation.Validators.EmailValidator..ctor () [0x00000] in \src\FluentValidation\Validators\EmailValidator.cs:33
    at FluentValidation.DefaultValidatorExtensions.EmailAddress[LoginPageViewModel] (IRuleBuilder`2 ruleBuilder) [0x00000] in \src\FluentValidation\DefaultValidatorExtensions.cs:127 `
    at  --- MYCODE

And the stacktrace for « .Length(x, x) »:

    at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed) [0x0011b] in /Developer/MonoTouch/Source/mono/mcs/class/corlib/System/Delegate.cs:229 
    at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) [0x00000] in /Developer/MonoTouch/Source/mono/mcs/class/corlib/System/Delegate.cs:293 
    at System.Reflection.MethodInfo.CreateDelegate (System.Type delegateType, System.Object target) [0x00000] in /Developer/MonoTouch/Source/mono/mcs/class/corlib/System.Reflection/MethodInfo.cs:174 
    at FluentValidation.Internal.Compatibility.CreateGetter (System.Reflection.PropertyInfo property) [0x00000] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Internal\\Compatibility.cs:55 
    at FluentValidation.Resources.StaticResourceAccessorBuilder.GetResourceAccessor (System.Type resourceType, System.String resourceName) [0x00064] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Resources\\IResourceAccessorBuilder.cs:42 
    at FluentValidation.Resources.LocalizedStringSource..ctor (System.Type resourceType, System.String resourceName, IResourceAccessorBuilder resourceAccessorBuilder) [0x00006] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Resources\\LocalizedStringSource.cs:40 
    at FluentValidation.Resources.LocalizedStringSource.CreateFromExpression (System.Linq.Expressions.Expression1 expression, IResourceAccessorBuilder resourceProviderSelectionStrategy) [0x00043] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Resources\\LocalizedStringSource.cs:68 
    at FluentValidation.Validators.PropertyValidator..ctor (System.Linq.Expressions.Expression1 errorMessageResourceSelector) [0x00011] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Validators\\PropertyValidator.cs:54 
    at FluentValidation.Validators.LengthValidator..ctor (Int32 min, Int32 max, System.Linq.Expressions.Expression`1 errorMessageResourceSelector) [0x00000] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Validators\\LengthValidator.cs:32 
    at FluentValidation.Validators.LengthValidator..ctor (Int32 min, Int32 max) [0x00000] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\Validators\\LengthValidator.cs:29 
    at FluentValidation.DefaultValidatorExtensions.Length[LoginPageViewModel] (IRuleBuilder`2 ruleBuilder, Int32 min, Int32 max) [0x00000] in c:\\Projects\\FluentValidation\\src\\FluentValidation\\DefaultValidatorExtensions.cs:66 
    at ----MYCODE

Downgrading to 5.5.0.0 fixed the issue, I had not enough time to investigate on why it crashed.

All seems to get down to https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Internal/Compatibility.cs
Maybe this is a bug on mono ?

Hoping this helps you, do not hesitate to contact me for more infos on this.

**Comment by Allann** [comment] 2015-05-26 01:45
I get a slightly different error, but I don't use Xamarin.

System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
  Source=mscorlib
  StackTrace:
       at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
       at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType, Object target)
       at FluentValidation.Internal.Compatibility.CreateGetter(PropertyInfo property)
       at FluentValidation.Resources.StaticResourceAccessorBuilder.GetResourceAccessor(Type resourceType, String resourceName)
       at FluentValidation.Resources.LocalizedStringSource..ctor(Type resourceType, String resourceName, IResourceAccessorBuilder resourceAccessorBuilder)
       at FluentValidation.Resources.LocalizedStringSource.CreateFromExpression(Expression`1 expression, IResourceAccessorBuilder resourceProviderSelectionStrategy)
       at FluentValidation.Validators.PropertyValidator..ctor(Expression`1 errorMessageResourceSelector)
       at FluentValidation.Validators.AbstractComparisonValidator..ctor(IComparable value, Expression`1 errorMessageSelector)
       at FluentValidation.Validators.LessThanOrEqualValidator..ctor(IComparable value)
       at FluentValidation.DefaultValidatorExtensions.LessThanOrEqualTo[T,TProperty](IRuleBuilder`2 ruleBuilder, TProperty valueToCompare)
       at Jbssa.Core.Client.ValidatableModelValidator`1..ctor()
       at Jbssa.Forms.Windows.Validators.CategoryValidator..ctor()
  InnerException: 

Again, going back to 5.5.0.0 fixed the issue.

**Comment by PaulAchess** [comment] 2015-05-26 07:59
I noticed a difference between #PORTABLE, with `property.GetMethod` passed (Compatibility.cs:55), and the other cases, with `property.GetGetMethod()` (Compatibility.cs:57).

Could it be `GetMethod()` instead of `GetMethod` ? Or even `GetGetMethod()` also ?

It seems `property.GetMethod` is not of type `Fun<string>`

**Comment by PaulAchess** [comment] 2015-05-26 08:07
To add something (if this helps), my class inherits from a ValidableViewModelBase which inherits from a ViewModelBase.

**Comment by JeremySkinner** [comment] 2015-05-28 09:13
I don't have xamarin installed, so can't test it with that, but if you could put together a small project that reproduces the problem (with just regular PCLs) then that would be very helpful. Thanks.

**Comment by PaulAchess** [comment] 2015-05-28 09:20
I'm a bit on the rush this week, @Allann would you have the time to do so ? I'll try to do this this week-end if you can't.

**Comment by Allann** [comment] 2015-05-28 13:38
I'll see if I cab come up with something over the weekend.

Sent from my Windows Phone
________________________________

**Comment by jeffdoolittle** [comment] 2015-05-28 16:59
Just ran into a similar issue - using Xamarin as well. All of my "RuleFor" methods are failing to execute with an ArgumentException like this:

{System.ArgumentException: method argument length mismatch
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed) [0x0011b] in /Users/builder/data/lanes/1799/3c4e832a/source/mono/mcs/class/corlib/System/Delegate.cs:229 
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) [0x00000] in /Users/builder/data/lanes/1799/3c4e832a/source/mono/mcs/class/corlib/System/Delegate.cs:293 
  at System.Reflection.MethodInfo.CreateDelegate (System.Type delegateType, System.Object target) [0x00000] in /Users/builder/data/lanes/1799/3c4e832a/source/mono/mcs/class/corlib/System.Reflection/MethodInfo.cs:152 
  at FluentValidation.Internal.Compatibility.CreateGetter (System.Reflection.PropertyInfo property) [0x00000] in c:\Projects\FluentValidation\src\FluentValidation\Internal\Compatibility.cs:55 
  at FluentValidation.Resources.StaticResourceAccessorBuilder.GetResourceAccessor (System.Type resourceType, System.String resourceName) [0x00064] in c:\Projects\FluentValidation\src\FluentValidation\Resources\IResourceAccessorBuilder.cs:42 
  at FluentValidation.Resources.LocalizedStringSource..ctor (System.Type resourceType, System.String resourceName, IResourceAccessorBuilder resourceAccessorBuilder) [0x00006] in c:\Projects\FluentValidation\src\FluentValidation\Resources\LocalizedStringSource.cs:40 
  at FluentValidation.Resources.LocalizedStringSource.CreateFromExpression (System.Linq.Expressions.Expression`1 expression, IResourceAccessorBuilder resourceProviderSelectionStrategy) [0x00043] in c:\Projects\FluentValidation\src\FluentValidation\Resources\LocalizedStringSource.cs:68 
  at FluentValidation.Validators.PropertyValidator..ctor (System.Linq.Expressions.Expression`1 errorMessageResourceSelector) [0x00011] in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:54 
  at FluentValidation.Validators.NotNullValidator..ctor () [0x00000] in c:\Projects\FluentValidation\src\FluentValidation\Validators\NotNullValidator.cs:23 
  at FluentValidation.DefaultValidatorExtensions.NotNull[NewHireCreateModel,String] (IRuleBuilder`2 ruleBuilder) [0x00000] in c:\Projects\FluentValidation\src\FluentValidation\DefaultValidatorExtensions.cs:43 
 
@PaulAchess or @Allann let me know if I can help in any way because I'm pretty much stuck until this is fixed.

**Comment by Allann** [comment] 2015-05-29 04:43
@jeffdoolittle - i'd role back to 5.5 for now unless @JeremySkinner can advise of a release date.

**Comment by PaulAchess** [comment] 2015-05-29 07:29
@jeffdoolittle Same here, use this on the related project: 
Uninstall-Package FluentValidation -Force
Install-Package FluentValidation -Version 5.5.0.0

**Comment by JeremySkinner** [comment] 2015-05-29 07:59
I'll aim to get a fix out as quickly as possible.

It would be really helpful to know which PCL you have referenced - a while back I split the PCLs into a net40 and a net45 version, in preparation for asp.net vNext and it's new runtime, and these were both included in the FV 5.6 release.

Are you all referencing the one in the portable-net40 or the portable-net45 subdirectory of the package?

**Comment by PaulAchess** [comment] 2015-05-29 08:19
I'm on a portable-net45.

The exact line of the package.config:
targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10"

Good luck for this bug!

**Comment by JeremySkinner** [comment] 2015-05-29 10:47
OK, don't worry about creating a repro project - I have one using normal PCLs. Will post an update when I get it fixed.

**Comment by Allann** [comment] 2015-05-29 11:51
excellent.  I was just about to start.  I too was using the 45 version.

**Comment by JeremySkinner** [comment] 2015-05-29 12:22
I've committed a fix and 5.6.1 package is published. Please give it a go and let me know if you run into any other issues.

I've also made sure that the test suite now gets run against both the desktop build and the PCL build, which should hopefully stop more issues like this in the future.

**Comment by PaulAchess** [comment] 2015-05-29 12:41
This looks good on my project. Good job !

You're the best.

**Comment by JeremySkinner** [comment] 2015-05-29 12:41
Great - glad it's working.

**Comment by Allann** [comment] 2015-05-29 14:56
Seems to be working here too.  Thanks heaps.

Sent from my Windows Phone
________________________________

**Comment by JeremySkinner** [comment] 2015-05-29 15:11
Great - I'll close this for now.

**Closed by JeremySkinner** 2015-05-29 15:11 UTC

**Comment by jeffdoolittle** [comment] 2015-05-29 23:20
Thanks!

**Comment by hoghweed** [comment] 2015-12-23 14:05
Hi
after upgrading to 6.0.0.0 version I got the same error "Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type." Downgrading to 5.6.2.0 fix the problem, any suggestion?

Thanks

**Comment by JeremySkinner** [comment] 2015-12-23 14:09
Please could you open a separate issue, and post some more details about your setup there? (Target platform, which do you're referencing etc)

**Comment by MridulMalviya** [comment] 2018-01-08 11:56
Hi i am using fluent validation for ui fileds in viewmodel how to update or highlight ui components when validation fails?
