### ISSUE TITLE
System.AccessViolationException System.AccessViolationException

### ISSUE THREAD

**Issue by mattdone01** [JeremySkinner/FluentValidation#94] opened 2015-07-10 06:09 UTC
Hi,
  We keep getting a number of errors in our system that always have a very similar stack trace. Have you seen anything like this before. We are using FluentValidation.5.5.0.0

<strong>Here is one stack trace.</strong>
An unhandled error has occurred in Nine.Saturn.Services.Campaigns.Service.CampaignEndpoint. | System.AccessViolationException System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FluentValidation.Internal.Extensions.<>c__DisplayClass1`2.<CoerceToNonGeneric>b__0(Object x) in c:\Projects\FluentValidation\src\FluentValidation\Internal\Extensions.cs: line 108
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue() in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidatorContext.cs: line 53
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs: line 68
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs: line 234
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList(IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs: line 113
   at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow(IValidator`1 validator, T instance) in DefaultValidatorExtensions.cs: line 791
   at Nine.Saturn.Services.Campaigns.DomainLogic.SpotOperations.SpotBookingOperationService.PlaceNewSpot(SpotParameters parameters, SpotOperationOptions operationOptions, BookingSource bookingSource) in SpotBookingOperationService.cs: line 172
   at Nine.Saturn.Services.Campaigns.DomainLogic.SpotOperations.SpotBookingOperationService.PlaceBooking(NormalBookingRequest bookingRequest, Nullable`1 auditTransactionType, Boolean publishChangeNotifications) in SpotBookingOperationService.cs: line 143
   at Nine.Saturn.Services.Campaigns.Service.CampaignEndpoint.PlaceBooking(NormalBookingRequest bookingRequest) in CampaignEndpoint.cs: line 516
   at SyncInvokePlaceBooking(Object, Object[], Object[])
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(ref MessageRpc rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

<strong>and Here is another stack trace</strong>
An unhandled error has occurred in Nine.Saturn.Services.Campaigns.Service.CampaignEndpoint. | System.AccessViolationException System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FluentValidation.Internal.Extensions.<>c__DisplayClass1`2.<CoerceToNonGeneric>b__0(Object x) in c:\Projects\FluentValidation\src\FluentValidation\Internal\Extensions.cs:line 108
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue() in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidatorContext.cs:line 53
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidator.cs:line 68
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 234
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow[T](IValidator`1 validator, T instance) in c:\Projects\FluentValidation\src\FluentValidation\DefaultValidatorExtensions.cs:line 791
   at Nine.Saturn.Services.Campaigns.DomainLogic.SpotSearchService.SearchSpots(PagingContext pagingContext, SpotSearchRequest searchRequest) in d:\SourceControl\SaturnProd\Services\Campaigns.DomainLogic\SpotSearchService.cs:line 160
   at SyncInvokeSearchSpots(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

**Comment by JeremySkinner** [comment] 2015-07-10 08:12
No I've not seen this before. 

Can you reproduce it in a unit test or a standalone project?

**Comment by mattdone01** [comment] 2015-07-10 08:35
No. It only seems to happen under heavy load. It is a wierd one. If you can
think of anything it would be much appreciated.

Matt

**Comment by gtaylor55sumtio** [comment] 2015-07-16 22:53
So I just started seeing this also. In my case it started happening after about 3 hours of running a data load process. I had three agents running in separate xunit processes and they all crashed after about 3 hours with this error. We're on 5.5.0.0. 

System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FluentValidation.Internal.Extensions.<>c__DisplayClass1`2.<CoerceToNonGeneric>b__0(Object x) in c:\Projects\FluentValidation\src\FluentValidation\Internal\Extensions.cs:line 
108
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue() in c:\Projects\FluentValidation\src\FluentValidation\Validators\PropertyValidatorContext.cs:line 53
   at FluentValidation.Validators.PropertyValidator.Validate(PropertyValidatorContext context) in c:\Projects\FluentValidation\src\FluentValidation\Validators
\PropertyValidator.cs:line 68
   at FluentValidation.Internal.PropertyRule.<Validate>d__10.MoveNext() in c:\Projects\FluentValidation\src\FluentValidation\Internal\PropertyRule.cs:line 234
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FluentValidation.AbstractValidator`1.Validate(ValidationContext`1 context) in c:\Projects\FluentValidation\src\FluentValidation\AbstractValidator.cs:line 113
   at WebIZ.Common.Validators.ValidatorBase`1.Validate(T instance) in Common\Validators\ValidatorBase.cs:line 40
   at FluentValidation.DefaultValidatorExtensions.ValidateAndThrow[T](IValidator`1 validator, T instance) in c:\Projects\FluentValidation\src\FluentValidation
\DefaultValidatorExtensions.cs:line 791
   at Services.ServiceBase.Save[TEntity](TEntity entity, IValidator`1 validator, IDbContextScope scope) in c:\Services\ServiceBase.cs:line 172
   at Services.Services.CaseService.SaveCaseComplaint(CaseComplaint caseComplaint) in \Services\CaseService.cs:line 355
   at (Object , Object[] )
   at Ninject.Extensions.Interception.Invocation.InvocationBase.Proceed()
   at Ninject.Extensions.Interception.Wrapper.DynamicProxyWrapper.Intercept(IInvocation castleInvocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ICaseServiceProxy.SaveCaseComplaint(CaseComplaint caseComplaint)
   at IntegrationTests.DataLoad.Loaders.CaseLoader.Load(List`1 clinics, IServiceFactory serviceFactory, IIdResolver idResolver, TestContext testContext, List`1 users) in 
IntegrationTests\DataLoad\Loaders\CaseLoader.cs:line 68
   at IntegrationTests.DataLoad.DataLoader.load_data() in IntegrationTests\DataLoad\DataLoader.cs:line 78

**Comment by JeremySkinner** [comment] 2015-07-17 15:27
Unfortunately that's not really enough to go on. Unless there's some reliable steps to reproduce it there's not much I can do.

**Comment by benadam777** [comment] 2015-07-20 19:18
We've been running into the same issue that's causing the app pool to recycle:
Exception object: 00000001044a0790
 Exception type:   System.AccessViolationException
 Message:          Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 InnerException:   <none>
 StackTrace (generated):
     SP               IP               Function
     000000005204D160 000007FE9E65EEE9 FluentValidation!FluentValidation.Internal.Extensions+<>c__DisplayClassd`2[[System.__Canon, mscorlib],[System.Decimal, mscorlib]].<CoerceToNonGeneric>b__c(System.Object)+0x39
     000000005204D1B0 000007FE9E65EE79 FluentValidation!FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue()+0x29
     000000005204D1E0 000007FE9E65ECB7 FluentValidation!FluentValidation.Validators.PropertyValidator.Validate(FluentValidation.Validators.PropertyValidatorContext)+0x57
     000000005204D230 000007FE9E65E234 FluentValidation!FluentValidation.Internal.PropertyRule+<Validate>d__10.MoveNext()+0x274
     000000005204D2B0 000007FEF2B5ECAC System_Core_ni!System.Linq.Enumerable+<SelectManyIterator>d__14`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].MoveNext()+0x1fc
     000000005204D310 000007FEF3A355B9 mscorlib_ni!System.Collections.Generic.List`1[[System.__Canon, mscorlib]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)+0x219
     000000005204D380 000007FEF2B61201 System_Core_ni!System.Linq.Enumerable.ToList[[System.__Canon, mscorlib]](System.Collections.Generic.IEnumerable`1<System.__Canon>)+0x51
     000000005204D3C0 000007FE9E65DCCF FluentValidation!FluentValidation.AbstractValidator`1[[System.__Canon, mscorlib]].Validate(FluentValidation.ValidationContext`1<System.__Canon>)+0xaf
...

**Comment by JeremySkinner** [comment] 2015-07-21 08:05
That could indeed be the issue - the validators themselves are designed to be thread-safe, but PropertyValidatorContext is not. The idea was always that you can reuse the validator instances across threads, but not the context objects.

Here's the code for PropertyValue:

```
public object PropertyValue {
	get {
		if (!propertyValueSet) {
			propertyValue = Rule.PropertyFunc(Instance);
			propertyValueSet = true;
		}

		return propertyValue;
	}
	set {
		propertyValue = value;
		propertyValueSet = true;
	}
}
```

...as you can see, the property is lazily-loaded (and doesn't use any locking), so it's certainly possible that you could run into problems if you've got multiple threads trying to read from this property at once.

**Comment by benadam777** [comment] 2015-07-21 13:41
I'd really appreciate that.  I don't mean to sound like I'm rushing but what would the ETA be to have this in the next release?  We're considering removing FluentValidation to recover site stability since we run into this issue perhaps about once per week but we'd prefer to keep it, given how helpful it is.  Please let me know if I can be of any assistance.

**Comment by JeremySkinner** [comment] 2015-07-21 13:43
I'm away with work until early September, so not until then at the earliest I'm afraid. Your best bet would be to build from source and patch it yourself rather than wait for me to do a release.

**Comment by benadam777** [comment] 2015-07-21 13:45
Roger that.  I'll take a look and discuss with my colleagues.  Thanks for getting back to me on this so quickly.

**Comment by JeremySkinner** [comment] 2015-07-21 13:54
OK, let me know what you decide. I'm happy to make the change to the source - it should be fairly quick, but then you'd be 'on your own' with it until I'm back in September

**Comment by mattdone01** [comment] 2015-07-22 02:54
I'd prefer if you made the change, then we can pull the branch and rebuild. We can revert back to nuget when you release a new version. 

This happens to us about 3 times a day which is quite frustrating, so we'd really like to get a fix asap. Thanks Jeremy.

**Comment by JeremySkinner** [comment] 2015-07-22 07:46
I've committed the change. Please give it a try and let me know whether or not it seems to make a difference.

**Comment by benadam777** [comment] 2015-07-22 13:45
Thank you for the fast turnaround on this JeremySkinner.  We won't be able to determine whether this fix has addressed the issue until later this week or perhaps sometime next week when we can get it under load.  Mattdone01, would you please indicate whether this change has resolved the issue on your end when you have that information?  Thank You.

**Comment by gtaylor55sumtio** [comment] 2015-07-22 14:23
Thanks for looking at this Jeremy. Just to give everybody more info on this from our side, we are not in production yet and we saw the error during a lengthy data load process. There weren't multiple threads and was very much a serial process that ran. And it was a new instance of the validator on every save, but eventually it crashed after about 3 hours. Memory wasn't out of ordinary at the time of the crash. I'm having a hard time recreating it unfortunately.

**Comment by mattdone01** [comment] 2015-07-22 22:03
I will compile and test everything today and then put into production
tonight. I should know if it was successful by tomorrow afternoon 24th.

Matt

**Comment by benadam777** [comment] 2015-07-28 13:31
Hi Matt,

Any word back on the success of this fix?  We're at a point where we are ready to decide whether to remove the library or not and your feedback would be pivotal towards that decision.

Thank You.

**Comment by mattdone01** [comment] 2015-07-29 00:52
The code changes made by Jeremy have *not *made a difference. We are still
getting the same error with the same stack trace. We are now looking at
removing fluent validation for high volume server-side validations. UI
validations seem fine. If you have a ​large transaction​al​ system I'd
probably look at something else​, unless Jeremy can fix this issue. We get
about 3 service crashes a day​, we have 7 load balanced servers so it isn't
a major issue but still causes us a number of operational issues.

**Comment by JeremySkinner** [comment] 2015-07-29 06:48
Ok, I didn't think it would work, but it was worth a try.

Unfortunately I still have nothing to go on - I can't reproduce the issue,
and the stack trace isn't from any FV code itself (it's from invoking a
delegate).

Unless anyone has any suggestions on how to proceed I'm going to have to
park this for now.

**Comment by SeanKilleen** [comment] 2016-06-06 11:37
Cleanup: Closing this as it hasn't been active in some time. Feel free to re-open if necessary.

**Closed by SeanKilleen** 2016-06-06 11:37 UTC
