### ISSUE TITLE
Fluent validator makes 500 ErrorCode

### ISSUE THREAD

**Issue by OlekRia** [JeremySkinner/FluentValidation#866] opened 2018-08-17 05:42 UTC
I have created a .net core solution and bound FluentValidator to the project by manual. And for example this rule:
```
 public class CommandValidator : AbstractValidator<Command>
        {
            public CommandValidator()
            {
                RuleFor(x => x.ValueName).MinimumLength(2);
            }
        }
```
works pretty nice ! y controller returns Error 400 and proper message.
However, I have create another one:
```
            public CommandValidator(ITournamentDal tournamentDal)
            {
                RuleFor(x => tournamentDal.Get(x.TournamentId))
                    .NotNull();
            }
```

My controller returns 500 message with ugly response payload. I should note that tournamentDal.Get(x.TournamentId) works properly and returns Null.
And... I am just get lost. Please help.

P.S. "
FluentValidation.ValidationException: Validation failed: 
 -- '' must not be empty.
…..
…...
"

**Comment by JeremySkinner** [comment] 2018-08-17 07:19
Hi, please provide the following details:
- Which version of FluentValidation are you using?
- How are you invoking the validator? (Please provide the relevant code)

It sounds like you’re using ValidateAndThrow to throw an exception if the rule fails. If this is a web project then you shouldn’t be using ValidateAndThrow, you should be putting the errors into ModelState. 

Also, Rules should be against properties, but you’re calling a method inside your RuleFor. You should rewrite the rule to be directly against the TourtnamentId property, eg:

```
RuleFor(x => x.TournamentId).Must(id => tournamentDal.Get(id) != null).WithMessage(“Please specify a valid id”);
```

**Comment by OlekRia** [comment] 2018-08-17 10:33
`RuleFor(x => x.TournamentId).Must(id => tournamentDal.Get(id) != null).WithMessage(“Please specify a valid id”);`

Unfortunately, it works absolutely same.
I am using FluentValidation v7.6.105

in ASP.net core project. With Mediatr library.
`    public class Close
    {
        public class Command : IRequest
        {
            public Command(int tournamentId)
            {
                TournamentId = tournamentId;
            }

            public int TournamentId { get; }
        }

        public class CommandHandler : IRequestHandler<Command>
        {
            private readonly ITournamentDal _tournamentDal;

            public CommandHandler(ITournamentDal tournamentDal)
            {
                _tournamentDal = tournamentDal;
            }

            public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
            {
                await _tournamentDal.UpdateTournamentClose(request.TournamentId);
                return Unit.Value;
            }
        }

        public class CommandValidator : AbstractValidator<Command>
        {
            public CommandValidator(ITournamentDal tournamentDal)
            {
                RuleFor(x => x.TournamentId).Must(id => tournamentDal.Get(id) != null).WithMessage("Please specify a valid id");
            }
        }
    }`

**Comment by JeremySkinner** [comment] 2018-08-17 10:39
Hi, I can't help you with Mediatr I'm afraid, only FluentValidation, but if you're seeing that exception it means you're calling `ValidateAndThrow` to invoke the validator, rather than `Validate`. If the exception is being thrown then it means that the rule is failing (and the call to `tournamentDal.Get(id)` is returning null.

(also just a tip, formatting code blocks in github is done by 3 backticks).

**Comment by OlekRia** [comment] 2018-08-17 11:03
Mediatr is OK. Nothing special. Simply as you can see above, one Validation works and other not.
The main difference I found is constructor by default.

**Comment by JeremySkinner** [comment] 2018-08-17 11:05
I'm still having trouble understanding what's not working....as I said before, if you're seeing an error it means the rule is failing. What exactly isn't working for you?

**Comment by OlekRia** [comment] 2018-08-17 13:17
PLease view sample here:
https://github.com/OlekRia/Test125
And especially this one: https://github.com/OlekRia/Test125/blob/master/Duplicate.BJ.Application/Features/Tournaments/Close.cs
makes 500 error
but
https://github.com/OlekRia/Test125/blob/master/Duplicate.BJ.Application/Features/Values/Create.cs
makes 400 response with pretty payload as usual for FluentValidator

**Comment by JeremySkinner** [comment] 2018-08-17 13:48
The problem is your `ValidationPipelineBehavior` class:

https://github.com/OlekRia/Test125/blob/16bf468894b57e891a0e749944fb219ec6422d13/Duplicate.BJ.Bootstrapper/ValidationPipelineBehavior.cs#L19-L34

As I said previously, *you shouldn't be throwning an exception* - you should be adding the validation results to ModelState. 

Throwing an exception which is unhandled will cause ASP.NET to generate a 500 response. This isn't related to FluentValidation, that's just the standard behaviour of ASP.net when dealing with unhandled exceptions. If you add the results to ModelState, then a 400 response will be correctly generated. Your `ValidationActionFilter` will also never be called as the exception has already caused the request to fail.

The other command (https://github.com/OlekRia/Test125/blob/master/Duplicate.BJ.Application/Features/Values/Create.cs) does *exactly* the same thing, because of the ValidationPipelineBehaviour is throwing that exception. The other Create command (https://github.com/OlekRia/Test125/blob/16bf468894b57e891a0e749944fb219ec6422d13/Duplicate.BJ.Application/Features/Tournaments/Create.cs) does run, but that's only because the validator is not implemented, so is never being invoked.

I can see a couple of options:
- Find a way to inject the current ControllerContext into your ValidationPipelineBehavior and then copy the validtion results into the `ModelState` dictionary in here 
- Keep the ValidationPipelineBehavior as-is, but use an exception filter higher up the chain to catch the `ValidationException`, extract the failures from the exception add then results to ModelState inside the filter.

I am going to close this issue now as the problem is with your architecture rather than a problem with FluentValidation itself.

**Closed by JeremySkinner** 2018-08-17 13:48 UTC

**Comment by OlekRia** [comment] 2018-08-17 14:25
So this: https://stackoverflow.com/questions/42283011/add-validation-to-a-mediatr-behavior-pipeline
answer obviously is wrong!?

**Comment by JeremySkinner** [comment] 2018-08-17 14:30
Correct; by itself that isn’t a good answer. There needs to be a way to catch/handle the exception to copy the results to modelstate.

**Comment by JeremySkinner** [comment] 2018-08-17 15:01
The simplest way to make it work without if you don’t want to change the infrastructure would be to wrap the call to mediatr in your controller action with a try/catch that handles the ValidationException, extracts the failures and copies them to modelstate. Not as elegant admin using a filter, but at least it’s skmple.

**Comment by OlekRia** [comment] 2018-08-17 15:05
I will try. Not easy to understand, however. Simply Mediatr uses this sample as official feature (using validation in pipelining) in the way I just described above.
Anyway, it's hard to understand why Value Create is OK and Tournament Create is not. They seem really absolutely same !

**Comment by JeremySkinner** [comment] 2018-08-17 15:08
I tried your application and ValueCreate actually does exactly the same thing if validation fails. 

I’m out at the moment but will try and post an example later when I’m home to try and make it easier to understand.

**Comment by OlekRia** [comment] 2018-08-17 15:26
OK. Howerver, it's really hard to understand the difference between two Creates.

When I go to ValueCreate I don't even go to pipeline in Mediatr.

**Comment by JeremySkinner** [comment] 2018-08-17 15:55
This is what I meant by handling the exception and copying the messages to ModelState:

```csharp
[HttpPut("{tournamentId}")]
[ProducesResponseType(204)]
public async Task<IActionResult> Close(int tournamentId)
{
    try
    {
        await _mediator.Send(new Close.Command(tournamentId));
    }
    catch (ValidationException ex)
    {
        CopyValidationErrorsToModelstate(ex);
        return this.ValidationProblem();
    }

    return NoContent();
}

private void CopyValidationErrorsToModelstate(ValidationException validationException)
{
    foreach (var error in validationException.Errors)
    {
        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
    }
}

```

**Comment by OlekRia** [comment] 2018-08-17 18:39
Your approach is good, but would be better if we don't make this error check for each controller action. Guess it could be nice to pass somehow model state to pipeline somehow.
