### ISSUE TITLE
Breaking change found: NULL instance is not allowed to be passed into validator

### ISSUE THREAD

**Issue by a13531a** [JeremySkinner/FluentValidation#486] opened 2017-06-12 04:06 UTC
Hello,

I was a little disappointed when I upgraded from v6.2.1 to v7.0.3. I encountered with a breaking change that was introduced in v6.4 (March 3, 2017). It is not possible to pass NULL value into the validator anymore starting from v6.4. I don't know if it is by design or it is something that was not planned (sort of side-effect).

For example, I cannot have something like this:

    public class CreateFolderRequestValidator : AbstractValidator<CreateFolderRequest>
    {
        public CreateFolderRequestValidator()
        {
            RuleFor(x => x).NotNull();
            When(x => x != null, () =>
            {
                // Validation rules...
            });
        }
    }

The ArgumentNullException is thrown when NULL is passed into the ValidateAndThrow method with the following message:
Value cannot be null. Parameter name: Cannot pass null model to Validate.

Before v6.4, I could check for NULL value in the validator, but now I have to do it EVERYWHERE outside of the validator. I need to write this extra check for NULL before every call to the ValidateAndThrow method which (to me) should really be up to the validator.

Please, consider this case. Please, make it possible to check for NULL inside of the validator so that no ArgumentNullException would be thrown. Or at least, it would be great if there would be a way to configure this behavior. Maybe, there could be some default behavior and this behavior could be changed in the validator's constructor like, for example, "AllowNullInstance = true" or something like this.

Thank you.

**Comment by JeremySkinner** [comment] 2017-06-12 05:56
This is actually by design. The purpose of FluentValidation is to validate properties on objects, which by definition requires a non-null instance in order to work. 

Most people using FV would not explicitly check for null and then would be confused when they encountered NullReferenceExceptions when passing a null instance into the validator. There were also other places I nth code that simply assumed the instance was always non-null. Introducing the null check in the Validate method fixes this and makes it explicit. 

In your case this is a bit different though as you were actually always checking for null explicitly anyway. 

I don't really want to add a property to turn this off as it really is a requirement of FV being able to work correctly. Would it work for you if I were to add a virtual method that you could override on AbstractValidator? That way you could disable this if you want to without the ability to disable it being explicitly part of th public api.

**Comment by a13531a** [comment] 2017-06-12 15:30
Thank you for your response. I would appreciate any decision that would allow to bypass the guard clause for NULL instance including a virtual method that could be overridden in a derived class. Of course, this NULL checking makes sense to me. I see the point here. And in many places I will definitely take advantage of this out-of-the-box check, but there still some places in my Web API project where I would prefer the ValidationException to be thrown instead of the ArgumentNullException. That way I can easily distinguish between exceptions from FV and from my code.

Thank you for this flexibility that FV has. I appreciate your quick response FluentValidation is a great package and it has been a joy to use it.

**Comment by JeremySkinner** [comment] 2017-06-13 10:34
I've add a virtual method to AbstractValidator called EnsureInstanceNotNull. Just override this so the method is a no-op, and the exception won't be thrown. This is checked in, and I'll try and do a release in the next few days.

**Comment by a13531a** [comment] 2017-06-14 01:09
Thank you. That is awesome!

**Closed** 2017-06-14 01:16 UTC

**Comment by MaikuMori** [comment] 2017-12-03 23:57
This has interesting interaction .NET Core with

```
services.AddMvc().AddFluentValidation(fv => {
 fv.ImplicitlyValidateChildProperties = true;
});
```

If you have classes which have other classes (with validation) as fields and you want to allow them to be optional, it just throws error even when using `when` or `unless`.

**Comment by JeremySkinner** [comment] 2017-12-04 08:08
@MaikuMori that’s probably a bug....if the property is null then FV is supposed to be skipped - could you open a separate issue for this? Thanks
