### ISSUE TITLE
Cannot access a disposed object. Injection in Validator in ASP.NET Core.

### ISSUE THREAD

**Issue by mdmoura** [JeremySkinner/FluentValidation#306] opened 2016-07-29 14:00 UTC
I am using Fluent Validation with ASP.NET Core and I have the following on Startup:

```
  services.AddDbContext<Context>(x => x.UseSqlServer(connectionString));

  services.AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<Startup>());
```

Then I have the following Validator:

```
public class TestModelValidator : AbstractValidator<TestModel> {
    public TestModelValidator(Context context) {  
    }
}
```

When I submit the model I get the error:

```
ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur is you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: Context
```

I think Validators are being registered as Singletons. Doesn't create a problem in some scenarios?

What is the best way to solve this?

Thank you

**Comment by JeremySkinner** [comment] 2016-07-29 18:08
Yes it's because the validators are singletons. Either register them as
transient (but there's a performance implication for this) or don't inject
the context directly and instead resolve it on the fly.

**Comment by mdmoura** [comment] 2016-07-29 18:12
You mean having:

    public class TestModelValidator : AbstractValidator<TestModel> {
        public TestModelValidator() {  
            using (Context context = new Context()) {
            }
        }
    }

In relation to register the Validators as transient you mean (using Autofac):
        x.RegisterAssemblyTypes(Assembly.GetEntryAssembly()).AsClosedTypesOf(typeof(IValidator<>)).AsImplementedInterfaces().InstancePerLifetimeScope();

I suppose using the extensions:

    services.AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<Startup>());

Always registers the validators as singletons, right?

**Comment by JeremySkinner** [comment] 2016-07-29 18:15
I meant injext a Func<DbContext> or a IContextProvixer or something like
that which can create the context when you need it. Don't instantiate it
directly in the validator.

**Comment by mdmoura** [comment] 2016-07-29 18:18
In fact I have tried:

    public class TestModelValidator : AbstractValidator<TestModel> {
        public TestModelValidator(Func<Context> context) {  
        }
    }

As I use it in MVC5 but I got the same error. The only way I was able to solve this was by removing:

    services.AddFluentValidation(x => x.RegisterValidatorsFromAssemblyContaining<Startup>());

And add:
      autofacBuilder.RegisterAssemblyTypes(Assembly.GetEntryAssembly()).AsClosedTypesOf(typeof(IValidator<>)).AsImplementedInterfaces().InstancePerLifetimeScope();

**Comment by JeremySkinner** [comment] 2016-07-30 09:05
I think I'll modify the default registration process to register the
validators as transient instead, which will avoid this problem for the next
release.

I've made some progress recently on improving the performance of validator
instantiation so making this change shouldn't have such a big performance
hit as it did before.

**Comment by mdmoura** [comment] 2016-07-30 09:19
You could always leave an option for people to choose which one want, being Transient the default one.

Any ETA for the next release?

**Comment by mdmoura** [comment] 2016-08-01 10:27
BTW, does it make any sense to keep Func<Context> in Validators when the Validators are Transient?

**Comment by JeremySkinner** [comment] 2016-08-02 11:53
No if the validator is transient you should be able to just inject the context directly.

**Comment by GFoley83** [comment] 2017-08-24 08:41
Hi Jeremy, I've got a similar issue with FV 7.1.1 in a .NET 4.6 framework application at the moment. There's an issue open on stackoverflow which is identical to the problem I'm having
https://stackoverflow.com/q/45769828/654708
whereby the Db context is marked as disposed for everything but the first validation request because the concrete implementations of `IValidator` are always singletons. This is despite the fact that they're being registered as Transient with the IoC.
`container.Register(typeof(IValidator<>), assemblies, Lifestyle.Transient);`

Injecting a Func reference to the DbContext works fine but I'd still like to know where the fault lies here. Any ideas?

**Comment by JeremySkinner** [comment] 2017-08-24 08:49
@GFoley83 Hard to know without seeing the code, but this will definitely be a configuration issue rather something being wrong with FV. 

The only thing I'd suggest checking is making sure you don't have any singleton-scoped objects that have a dependency on a transient validator, otherwise they'll be holding on to the reference.

If you want to put together a small sample project that reproduces the problem then I'd be happy to take a look.

**Comment by GFoley83** [comment] 2017-08-24 08:56
@JeremySkinner Thanks a million. My setup is the same as that stack issue (that has sample code), I'm also using SimpleInjector. Nothing is set up as a singleton (just a scoped async lifestyle), which is what's baffling me. Happy to setup a small poc though.

**Comment by JeremySkinner** [comment] 2017-08-24 08:57
@GFoley83 Yes please - a zip of a small project that I can just execute would be helpful.

**Closed** 2017-12-08 10:56 UTC

**Comment by aggroskater** [comment] 2018-03-28 21:55
I've encountered the same issue as @GFoley83 and the person in the stackoverflow link:

https://stackoverflow.com/q/45769828/654708

I've got an example project here --with SimpleInjector and FluentValidation, a small AbstractValidator on one of the included models, and configured Startup.cs-- which includes a commit with the known state that reproduces the issue (the latest commit has the "fix"):

https://github.com/aggroskater/webapi-fluentvalidation-simpleinjector-example

You can start the project, set a breakpoint inside the `RegisterBindingModelValidator` constructor, and then hit this endpoint with a malformed POST body (something like `{"Email": null}` would work):

http://localhost:64287/api/Account/Register [dunno if the port changes or not]

If the following line in `Startup.cs` is commented out, the the `RegisterBindingModelValidator` constructor breakpoint is only hit once:

```
configuration.Services.Clear(Type.GetType("System.Web.Http.Validation.IModelValidatorCache, System.Web.Http"));
```

Otherwise, the constructor is hit every time, as would be intended/desired/expected for a scoped validator.

--------------------------------------------------------------------------------------

I'm not a .NET expert by any means, but I believe I understand where the problem is here. So far as I can tell, WebApi caches model validators (`IModelValidatorCache`) internally/on its own (from what I can tell, it caches them indefinitely, so they are always singletons effectively). So, even though FluentValidation is correctly using the DI container to instantiate the validators and their dependencies with the correct scopes, WebApi itself is caching the resulting validators indefinitely, effectively overriding the DI container. The first API call generates the validator, and subsequent API calls use the cache. If there are DbContexts managed by the DI container that are supposed to be scoped to the request, then it makes sense that subsequent API calls will fail; the expectation was that you'd get a new AbstractValidator every time, not the one from before (whose dependencies have already been disposed).

I was tipped off to this by the following stackoverflow page:

https://stackoverflow.com/questions/15092809/dependency-injected-validation-in-web-api

and this answer in particular:

https://stackoverflow.com/a/32259227

However, the answer also says that its an internal interface/service and it's not recommended to turn it off (but with no indication of *why* you wouldn't turn it off). I've experimented with turning it off with an internal project for `$job` --not in a rigorous manner, mind you, just staring at my watch and counting the seconds-- and there is a hit to API performance which tends to scale linearly with the complexity of the triggered AbstractValidator. More complex AbstractValidators take longer to instantiate than simpler ones (Sidenote: singleton validators are only instantiated once, as expected). Mind you, we don't have strong integration testing in place yet either, so I couldn't say if this broke anything else either as a result of turning off the `IModelValidatorCache`...

The `IModelValidatorCache` interface is `internal`, so I'm guessing that you can't just implement your own version of it that holds on to Singletons, transients, scoped, etc as appropriate for whatever DI container is in use.

--------------------------------------------------------------------------------------

All this being said... is it safe to disable the `IModelValidatorCache` if your DI container is going to be responsible for handling validator lifetimes? I mean, the DI container effectively *is* the cache at that point, no? Just a cache that lets you do more than just singleton validators...

The only other option I'm aware of is to do what my first stackoverflow link suggests ("Update 2"), where a singleton Func<> factory, that queries the container to get the instance, is used as the AbstractValidator's dependency. That feels more like a service locator pattern though, something that most people seem to advise against. And that *still* leaves the AbstractValidator as a singleton, so you don't necessarily avoid concurrency bugs either (the first request is halfway through validation with an injected _dep, and the second request comes in and re-sets the _dep, meaning the first request might not behave as expected since its _dep changed out from underneath itself... right?)

I eagerly await comments from someone more knowledgeable than myself.

**Comment by JeremySkinner** [comment] 2018-03-29 08:06
@aggroskater This is an old/closed issue to do with registering validators in asp.net core (not WebApi) - this is not related to what you're seeing. 

Please open a separate issue to discuss this, including which version of FluentValidation and FluentValidation.WebApi you're using. Thanks.
