### ISSUE TITLE
I'm trying to register fluentvalidation validators by using RegisterValidatorsFromAssemblyContaining but it's not working

### ISSUE THREAD

**Issue by bramzz** [JeremySkinner/FluentValidation#1134] opened 2019-05-23 16:21 UTC
### System Details

- FluentValidation version: 8.4.0
- Web Framework version: ASP.NET Core 2.2

### Issue Description

I'm trying to add FluentValidation to my project. I've added this piece of code in the Startup.cs

```
services
 .AddMvc()
 .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
 .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<LoginSplitPayUserCommandValidator>());

```

The validators are in a seperate assembly, hence why I can't use Startup.cs as a containing type.
I've tried registering the validators one by one too with the following code

```
services
 .AddMvc()
 .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
 .AddFluentValidation();

services.AddTransient<IValidator<LoginSplitPayUserCommand>, LoginSplitPayUserCommandValidator>();
```

That doesn't seem to work either. Am I missing something?

**Comment by JeremySkinner** [comment] 2019-05-23 16:23
That should work just fine - it’s the intended use of the method. 

Can you elaborate what you mean when you say it doesn’t work? If you debug and look at the container registrations you should see them in there, and what happens if you manually attempt to resolve the validator?

**Comment by bramzz** [comment] 2019-05-23 16:26
My breakpoint is never hit inside of the validator method, but I get no error either.

> If you debug and look at the container registrations 
I'm not sure how I can do this?

**Comment by JeremySkinner** [comment] 2019-05-23 16:30
> My breakpoint is never hit inside of the validator method, but I get no error either.

How are you invoking the validator? Your validator won't be instantiated until the framework attempts to perform validation. The validators are not instantiated when you register them with the container.

> I'm not sure how I can do this?

Literally just attempt to resolve the validator manually from the service provider.

**Comment by bramzz** [comment] 2019-05-23 16:37
I've tried manually resolving and that seems to work. I've also done what you said but unfortunately it returns null.

**Comment by JeremySkinner** [comment] 2019-05-23 16:38
I don't understand your previous comment. The code I asked you to run *is* manually resolving the validator...how can it both work and return null?

**Comment by bramzz** [comment] 2019-05-23 16:39
Sorry I might be misunderstanding what you mean. With manually resolving I thought you ment the following
```
CreateSplitPayUserCommandValidator validator = new CreateSplitPayUserCommandValidator();
ValidationResult valResult = validator.Validate(request);
```

**Comment by JeremySkinner** [comment] 2019-05-23 16:44
No, that's just instantiating the validator class directly. What I asked you to do was to manually resolve the validator from the service provider (which tests that your registrations have been run), and what ASP.NET Core does internally to instantiate the validator.

If that's returning null then it sounds like a problem somewhere in your Startup class, not with FluentValidation itself. Make sure that `ConfigureServices` in your startup is definitely being run (stick a breakpoint in there).

**Comment by bramzz** [comment] 2019-05-23 16:46
It passes the code in the startup, I just verified

**Comment by JeremySkinner** [comment] 2019-05-23 16:47
Paste your full startup class please.

**Comment by bramzz** [comment] 2019-05-23 16:48
```
using AutoMapper;
using FluentValidation.AspNetCore;
using MediatR;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using SplitPay.Application.Entities.SplitPayUserEntity.Commands;
using SplitPay.Application.Infrastructure;
using SplitPay.Application.Infrastructure.AutoMapper;
using SplitPay.Application.Interfaces;
using SplitPay.Application.Models;
using SplitPay.Domain;
using SplitPay.Persistence;
using Swashbuckle.AspNetCore.Swagger;
using System;
using System.Reflection;
using System.Text;

namespace SplitPay.WebApi
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add MediatR
            services.AddMediatR(typeof(CreateSplitPayUserCommandHandler).GetTypeInfo().Assembly);

            services.AddScoped<ISplitPayDbContext, SplitPayDbContext>();
            services.AddSingleton<IJwtFactory, JwtFactory>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            // Add DbContext using SQL Server Provider
            services.AddDbContext<SplitPayDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("SplitPayDatabase")));

            // Register the ConfigurationBuilder instance of FacebookAuthSettings
            services.Configure<FacebookAuthSettings>(Configuration.GetSection(nameof(FacebookAuthSettings)));

            // jwt wire up
            // Get options from app settings
            var jwtAppSettingOptions = Configuration.GetSection(nameof(JwtIssuerOptions));
            var _signingKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["JwtIssuerOptions:Key"]));

            // Configure JwtIssuerOptions
            services.Configure<JwtIssuerOptions>(options =>
            {
                options.Issuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)];
                options.Audience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)];
                options.SigningCredentials = new SigningCredentials(_signingKey, SecurityAlgorithms.HmacSha256);
            });

            var tokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)],

                ValidateAudience = true,
                ValidAudience = jwtAppSettingOptions[nameof(JwtIssuerOptions.Audience)],

                ValidateIssuerSigningKey = true,
                IssuerSigningKey = _signingKey,

                RequireExpirationTime = false,
                ValidateLifetime = true,
                ClockSkew = TimeSpan.Zero
            };

            // Add JWT Authentication
            //JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear(); // => remove default claims
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            }).AddJwtBearer(configureOptions =>
            {
                configureOptions.ClaimsIssuer = jwtAppSettingOptions[nameof(JwtIssuerOptions.Issuer)];
                configureOptions.TokenValidationParameters = tokenValidationParameters;
                configureOptions.SaveToken = true;
            });

            // Add identity
            var builder = services.AddIdentityCore<SplitPayUser>(u =>
            {
                // configure identity options
                u.Password.RequireDigit = false;
                u.Password.RequireLowercase = false;
                u.Password.RequireUppercase = false;
                u.Password.RequireNonAlphanumeric = false;
                u.Password.RequiredLength = 6;
            });
            builder = new IdentityBuilder(builder.UserType, typeof(IdentityRole), builder.Services);
            builder.AddEntityFrameworkStores<SplitPayDbContext>().AddDefaultTokenProviders();

            // Add AutoMapper
            services.AddAutoMapper(new Assembly[] { typeof(AutoMapperProfile).GetTypeInfo().Assembly });

            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "SplitPay API", Version = "v1" });
            });

            // Add fluent validation
            //Assembly _applicationAssembly = AppDomain.CurrentDomain
            //    .GetAssemblies()
            //    .SingleOrDefault(assembly => assembly.GetName().Name == "SplitPay.Application");

            //services.AddTransient<IValidator<CreateSplitPayUserCommand>, CreateSplitPayUserCommandValidator>();

            services
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<LoginSplitPayUserCommandValidator>()); // TODO FIX ASSEMBLY
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), 
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
                c.RoutePrefix = string.Empty;
            });

            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }
}

```

**Comment by JeremySkinner** [comment] 2019-05-23 16:50
I can't see anything obviously wrong there. Can you put together a small sample project that reproduces the issue? Thanks.

**Comment by bramzz** [comment] 2019-05-23 17:18
[SplitPay.zip](https://github.com/JeremySkinner/FluentValidation/files/3213397/SplitPay.zip)

**Comment by JeremySkinner** [comment] 2019-05-23 17:28
The test code to try resolving the validator is wrong. You currently have this:

```
var validator = HttpContext.RequestServices.GetService(typeof(IValidator<CreateSplitPayUserCommandValidator>));
```
As per my previous comment it should be: 
```
var validator = HttpContext.RequestServices.GetService(typeof(IValidator<CreateSplitPayUserCommand>)); 
```

The generic type parameter is the *type of object being validated*, which maps to the validator definition (ie `AbstractValidator<CreateSplitPayUserCommand>`). 

Once you fix that you will see that the validator *is* resolved correctly, so there is nothing wrong with your registrations.

**Comment by bramzz** [comment] 2019-05-23 17:30
Hmm ok, any idea why it's not working then?

**Comment by JeremySkinner** [comment] 2019-05-23 17:33
I'm a bit confused about what you're expecting to happen to be honest. 

Automatic validation happens for controller action parameters based off your registrations. Your controller action parameter is of type `UserRegistrationDto`, so ASP.NET Core will attempt to find a validator for this type, but there isn't one....your validator is for the `CreateSplitPayUserCommand`, so no automatic validation will happen.

Have you read the documentation at https://fluentvalidation.net/aspnet? It does explain how the automatic validation works.

**Comment by bramzz** [comment] 2019-05-23 17:41
Oh god, sorry for my stupidity. I've used it in another project for work and never figured that's how it exactly worked. Sorry for wasting your time.

**Comment by JeremySkinner** [comment] 2019-05-23 17:44
No problem. I'd recommend having a read of the asp.net core documentation on validation: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation This should give you some background into how validation works in ASP.NET Core. It's examples are all using DataAnnotations attributes rather than FluentValidation, but its the same principle, and explains clearly how the process works

**Comment by bramzz** [comment] 2019-05-23 17:45
Sorry, I know FluentValidation from work and they set it all up. I changed it to the dto and now it enters the validator but it doesn't throw an error or stop the flow. In my work project it did.

**Closed by JeremySkinner** 2019-05-23 17:44 UTC

**Comment by JeremySkinner** [comment] 2019-05-23 17:48
It won't throw an error - it populates `ModelState` with a collection of error messages. If you want to stop the flow you have to check `ModelState.IsValid`. Can I suggest that you please read the article I linked to about ASP.NET core validation before asking any further questions here. This is all explained in there. Thanks.
