### ISSUE TITLE
Validation message not showing (ASP.Net core + Autofac + FluentValidation)

### ISSUE THREAD

**Issue by binoypatel** [JeremySkinner/FluentValidation#387] opened 2017-01-25 15:53 UTC
Hi there,
I am working on ASP.Net Core application in which I want to do validation for the viewmodel. I cannot use [Validator] attribute on my viewmodel as they are in different assembly which I cannot reference to my Core assembly. My validator does work but when it returns the view back, it's not showing any validation messages. I have all the jquery libraries configured and included, in fact it was working with data annotation attributes (ie. Required, EmailAddress etc.) and showing messages in the browser. Here is the code:

1. WebApp.Core.dll

```
public class UserRegistrationViewModel
    {
        public string BusinessUnitName { get; set; }
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string PrimaryUserEmail { get; set; }
        public string PrimaryUserName { get; set; }
    }
```
2. WebApp.Business.dll
```
public sealed class UserRegistrationViewModelValidator :
AbstractValidator<UserRegistrationViewModel>
    {
        public UserRegistrationViewModelValidator(IEntitiesContext context)
        {
            RuleFor(vm => vm.BusinessUnitName)
                .NotEmpty();

            RuleFor(vm => vm.ConfirmPassword)
                .NotEmpty()
                .Equal(vm => vm.Password)
                .WithMessage(LocalizedStrings.ConfirmPasswordCompareErrorMessage);

            RuleFor(vm => vm.Password)
                .NotEmpty()
                .Length(6, 25);

            RuleFor(vm => vm.PrimaryUserEmail)
                .NotEmpty()
                .EmailAddress();

            RuleFor(vm => vm.PrimaryUserName)
                .NotEmpty()
                .Length(6, 50);
        }
    }
```
3. WebApp.dll (Startup.cs)
```
services
    .AddMvc()
    .AddFluentValidation(fv =>
fv.RegisterValidatorsFromAssemblyContaining<UserRegistrationViewModelValidator>());
```
 4. WebApp.dll (UserController.cs)
```
[AllowAnonymous]
[ValidateAntiForgeryToken]
[HttpPost]
public async Task<IActionResult> Registration(UserRegistrationViewModel viewModel)
{
	if (!ModelState.IsValid)
	{
		return View(viewModel);
	}
	string UserUrl = Request.GetRootUrl();
	var result = await _mediator.Send(new InsertQuery<UserRegistrationDto>
	{
		Dto = new UserRegistrationDto
		{
			BusinessUnitName = viewModel.BusinessUnitName,
			Email = viewModel.PrimaryUserEmail,
			Name = viewModel.PrimaryUserName,
			Password = viewModel.Password,
			Url = UserUrl
		}
	});
	if (!result.Succeed)
	{
		foreach (var error in result.Errors)
		{
			ModelState.AddModelError("", error);
		}
		return View(viewModel);
	}
	var appUser = await _userManager.FindByEmailAsync(viewModel.PrimaryUserEmail).ConfigureAwait(false);
	await _signInManager.SignInAsync(appUser, true).ConfigureAwait(false);
	return RedirectToAction("Index", "Home");
}
```
I am not sure what is missing, I couldn't find any example that shows the implementations I am looking for. Please note that I am using Autofac instead of default asp.not core IoC.

Thanks,
Binoy

**Comment by JeremySkinner** [comment] 2017-01-25 16:03
So this doesn't look right to me:

```
services
    .AddMvc()
    .AddFluentValidation(fv =>
fv.RegisterValidatorsFromAssemblyContaining<UserRegistrationViewModelValidator>());
```

...that registers the validators with MVC's built-in standard container. If you're using autofac then I'd expect to see you registering a custom ValidatorFactory with FV that calls into autofac instead.

**Comment by binoypatel** [comment] 2017-01-25 16:15
I see but I am passing all the registered services to autofac container here is a complete method:
```
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services
                .AddMvc()
                .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<UserRegistrationViewModelValidator>());

            services.UseDatabase(Configuration);

            services.RegisterIdentityServices();

            // Redis
            string redisServer = Configuration.GetValue<string>("RedisServer");
            if (!string.IsNullOrEmpty(redisServer))
            {
                services.UseRedisServer(redisServer);
            }
            else
            {
                services.UseCache();
            }

            var builder = new ContainerBuilder();
            builder.Populate(services);
            builder.RegisterModule<MediatorModule>();
            var container = builder.Build();
            return new AutofacServiceProvider(container);
        }
```

**Comment by JeremySkinner** [comment] 2017-01-25 16:17
Ok, is the validator definitely being invoked? Can you see entries in ModelState?

**Comment by binoypatel** [comment] 2017-01-25 16:22
Yeah, I can see errors in ModelState:
![image](https://cloud.githubusercontent.com/assets/4742252/22298981/72bb19ac-e2f0-11e6-87f7-932e7938ad5f.png)

**Comment by JeremySkinner** [comment] 2017-01-25 16:35
Ok so it looks like FluentValidation is all working fine....if the errors aren't showing up I'm not really sure what to suggest, as that's really an MVC problem at that point rather than an issue with FV. Do they show if you put a ValidationSummary on the page?

**Comment by binoypatel** [comment] 2017-01-25 16:40
I already have ValidationSummary on the page like this:

```
<form asp-controller="User" asp-action="Registration" data-ajax="true" data-ajax-method="POST">
                                <!--Body-->
                                <div asp-validation-summary="ModelOnly" id="divValidationSummary" class="text-danger wrapper"></div>
                                <div class="md-form">
                                    <i class="fa fa-cube prefix"></i>
                                    <input type="text" asp-for="BusinessUnitName" class="form-control" autofocus>
                                    <label asp-for="BusinessUnitName">@LocalizedStrings.CompanyPrompt</label>
                                    <span asp-validation-for="BusinessUnitName" class="text-danger" style="font-size:small;" />
                                </div>
```

If I add [Required] attribute to any of my ViewModel property, it just works fine, it shows the error message before post the form.

Thanks,
Binoy

**Comment by JeremySkinner** [comment] 2017-01-25 16:42
My experience with .net core is very limited, but doesn't the ValidationSummary work in the same way as previous versions of MVC (ie it just renders out the contents of modelstate in a list?)

**Comment by binoypatel** [comment] 2017-01-25 16:46
Yes, it does the same, for example if I put the simple password and click Register button then it POST the form to the server, on server it validates the password complexity and if it doesn't meet the minimum complexity then it throws the error and that error will be displayed in ValidationSummary on client side.

**Comment by JeremySkinner** [comment] 2017-01-25 16:47
Ok in that case I'm confused why it wouldn't be showing the entries added to ModelState by FV. Could you put together a small sample that reproduces the problem and send it to me? I'll then try and dig into it further....unfortunately I won't have a chance to look at it this week but I'll try and get to it next week.

**Comment by binoypatel** [comment] 2017-01-25 16:49
Sure, thanks for your time, I will have sample ready for you by this week and put it on git.

**Comment by binoypatel** [comment] 2017-01-25 22:58
Here is the sample, [https://github.com/binoypatel/AutoFac.Mediatr.Lab](https://github.com/binoypatel/AutoFac.Mediatr.Lab)
when you run the app, here is a brief

1. App shows two textboxes in browser
2. UnitName is first textbox and Password is second textbox
3. Password is decorated with [Required] in viewmodel
4. If you hit Register button with having Password empty, then you will see an error message (this is coming from DataAnnotation in Asp.Net Core)
5. Put some value in password (let say 'abc') and hit Register
6. you will see two errors in ModelState in Controller (Home.Index)

None of those errors will be displayed when sent back. Another problem is why it is doing POST in first place because both validations are failed and it should not POST until client-side errors removed. Like the way DataAnnotation works in asp.net core.

**Comment by JeremySkinner** [comment] 2017-01-26 10:06
The POST is expected as FluentValidation doesn't support clientside validation in .net core. I'll try and take a look at why the modelstate errors aren't showing up after the post next week.

**Comment by JeremySkinner** [comment] 2017-01-27 10:40
I had some time today so tried to look at this, but unfortunately the project won't run for me...the netcore runtime just gives me generic "Process failed" messages with nothing helpful in event viewer.

**Comment by JeremySkinner** [comment] 2017-01-27 11:12
Ok managed to get it working on another machine.  There's 2 problems...neither are related to FluentValidation (or autofac), but rather with how your view is defined.

First problem is with the validation summary:
```
<div asp-validation-summary="ModelOnly" id="divValidationSummary" class="text-danger wrapper"></div>
```
...that will only show model-level errors, but your validation rules are defined at the property level, not the model level, so none of the error messages will display here.  If you change asp-validation-summary to "All", then you'll see the FV messages show up:

```
<div asp-validation-summary="All" id="divValidationSummary" class="text-danger wrapper"></div>
```

Second issue is with the inline validation messages. This won't work:

```
<span asp-validation-for="UnitName" class="text-danger" style="font-size: small;" />
```

You must provide ending tags for tags using helpers in this way. Change it to this and the messages will show up:

```
<span asp-validation-for="UnitName" class="text-danger" style="font-size: small;"></span>
```

Hope that helps.

I'm going to close the issue now as it's not a problem with FV, but please feel free to open another issue if you run into any problems with FV itself.

**Closed by JeremySkinner** 2017-01-27 11:12 UTC

**Comment by JeremySkinner** [comment] 2017-01-28 09:55
Oh also, I forgot to mention that clientside support for FV .net core is on its way...probably in the next beta.

**Comment by binoypatel** [comment] 2017-01-30 21:46
Thank you very much for detailed testing and provided the solution, I will test this and update you if it doesn't work. It will be interesting to try new beta :)
