### ISSUE TITLE
.WithMessage() returns incorrect message with REPLACEMENT CHARACTER (�) when ã, é, ç...

### ISSUE THREAD

**Issue by danilobreda** [JeremySkinner/FluentValidation#1105] opened 2019-04-25 21:41 UTC
### ASP NET CORE 2.2

When using the FluentValidator .WithMessage:
`RuleFor(x => x.Login).NotEmpty().WithMessage("Login é obrigatório");`
The letter "é"and "ó" is converted to a replacement character "�". `"Login � obrigat�rio"` when the validation is called. `.Validate(entity)`

Its not a http problem, that because the problem is happening on my build machine, on my Test step. The validation test get a fail, the message is different from the original message.

> Failed   ComErro_Nome_Obrigatorio
> Error Message:
>  Expected resultUpdate.Errors to contain only items matching (x.ErrorMessage == value(xxxx.xxx.Tests.Validations.Entities.ApiValidationTest+<>c__DisplayClass2_0).erroRequerido), but {yyyy.yyy.Domain.Validators.DomainValidatorError
>    {
>       ErrorMessage = "Nome � obrigat�rio"
>       Field = "Nome"
>       Value = ""
>    }}  do(es) not match.

I can't debug it on my machine, because the problem persist only on my production and build machines (Linux, default language configurations[english]). I tried to run on a docker on my machine, with the version that is running on the production, and debug on visualstudio (docker debug), but im having some issues with docker right now.

[More Details about Replacement Character](https://en.wikipedia.org/wiki/Specials_(Unicode_block))

**Comment by JeremySkinner** [comment] 2019-04-26 08:24
This doesn’t really sound like an issue with FluentValidation...it sounds much more like an environmental problem, but if you can provide steps to reproduce it I’ll take a look.

**Comment by danilobreda** [comment] 2019-04-29 18:10
@JeremySkinner what kind of environmental problem this could be? They are running on docker, i cant imagine what it could be :/

**Comment by JeremySkinner** [comment] 2019-04-29 18:13
Does it work correctly outside of docker? If so then we can probably assume it’s related to your docket environment. 

Are you able to provide steps to reproduce?

**Comment by danilobreda** [comment] 2019-05-02 23:02
Same issue: https://github.com/dotnet/corefx/issues/31278

**Comment by danilobreda** [comment] 2019-05-02 23:16
Probably the problem is the [.NET Core Globalization Invariant Mode](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/globalization-invariant-mode.md) and a thing called ICU that probaly need to be installed on LINUX. My build machine and docker runs linux, i will wait for the response, probably thats the problem.

**Comment by JeremySkinner** [comment] 2019-05-03 09:59
Thanks for the update - that sounds likely. As this isn’t related to FluentValidation I’m going to go ahead and close this.

**Comment by danilobreda** [comment] 2019-05-07 02:53
@JeremySkinner  the problem is not (initially) the .net part as referenced before on this issue... after some Tests, I created a repository [**HERE**](https://github.com/danilobreda/FluentValidationBugLinux).
The problem persists only on my build machine, that is **LINUX** Ubuntu 18.03 with dotnet core 2.2(i think the version is irrelevant) installed.
On **windows** machine, the problem does not occurs!

### This is the steps using docker:

**(Ubuntu 18.04.2 LTS)**
docker pull ubuntu:latest  
docker run -it ubuntu:latest

**(inside the ubuntu instance now)**
apt-get update
apt-get install git-core
apt-get install wget

**(dotnet install part [Here](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-2.2.102))**
wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get install apt-transport-https
apt-get update
apt-get install dotnet-sdk-2.2

**(clone the git code)**
 git clone https://github.com/danilobreda/FluentValidationBugLinux.git /home/code
(now inside the UnitTestProject folder)
dotnet build .
dotnet test  .

**The result on linux is:**
Total tests: 3. Passed: 0. **Failed**: 3. Skipped: 0.
Test Run Failed.

**On windows the result is:**
Total tests: 3. **Passed**: 3. Failed: 0. Skipped: 0.
Test Run Passed.

----
The strange part is that nobody have reported this so far.
Im here for anything to help on it, 👍

**Comment by JeremySkinner** [comment] 2019-05-07 07:13
The problem is the file encoding of your test project. Take a look:

![image](https://user-images.githubusercontent.com/90130/57278951-b7f66500-709f-11e9-92ab-0d33067e57e7.png)

The actual message in the validator is encoded correctly:

![image](https://user-images.githubusercontent.com/90130/57278987-ca709e80-709f-11e9-9402-3a5619fdd18c.png)

**Closed** 2019-05-07 07:16 UTC
